Enhancement: fritzbox uptime display
gethomepage/homepage pull request #2481
Opened 2023-12-15 15:17 UTC by evorg

## Proposed change

- The uptime is now shown in days when it reaches the 24 hours (seconds will be hidden then)
- Days, hours & minutes will not be shown, is the uptime is not high enough
- Error messages are now returned correctly from the proxy

### Screenshots
Seconds:
![s](https://github.com/gethomepage/homepage/assets/4954274/3e856662-b2c3-4da9-94c6-90fd1d8a2924)

Minutes & Seconds:
![ms](https://github.com/gethomepage/homepage/assets/4954274/35ac493c-1b15-4936-9822-5238f48b3444)

Hours, Minutes & Seconds:
![hms](https://github.com/gethomepage/homepage/assets/4954274/a287f55e-894f-4e51-98c7-14fdbceeb9da)

Days, Hours & Minutes:
![dhm](https://github.com/gethomepage/homepage/assets/4954274/44388e0a-1f9b-4e1d-a1ad-f40a06ca75f8)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [x] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-12-15 21:00 UTC, shamoon requested changes

2023-12-15 21:00 UTC, shamoon commented on src/widgets/fritzbox/proxy.js
> +      res.status(500).json({ error: { message: error.message } });
```suggestion
      res.status(500).json({ error });
```

2023-12-15 21:06 UTC, evorg commented on src/widgets/fritzbox/proxy.js
> +      res.status(500).json({ error: { message: error.message } });
I tried exactly the same, but it didn't work... Any ideas? Can give it another try tomorrow!

2023-12-15 21:12 UTC, shamoon commented on src/widgets/fritzbox/proxy.js
> +      res.status(500).json({ error: { message: error.message } });
What didnt work? https://jsfiddle.net/fqdhoLw3/

2023-12-15 21:29 UTC, evorg commented on src/widgets/fritzbox/proxy.js
> +      res.status(500).json({ error: { message: error.message } });
Either the proxy response was completely empty or the error element.

2023-12-15 21:33 UTC, shamoon approved these changes

2023-12-15 21:33 UTC, merged

2023-12-15 22:13 UTC, shamoon commented
FYI, I refactored a few different uptime implementations (including this one) into one, its not 100% the same as yours in that it doesnt pad digits, but rather than having 4 different implementations floating around... =)

LMK if you have any concerns

2023-12-16 09:30 UTC, evorg commented on src/widgets/fritzbox/proxy.js
> +      res.status(500).json({ error: { message: error.message } });
- `res.status(500).json({ error: { message: error.message } });`
![Bildschirmfoto 2023-12-16 um 10 24 49](https://github.com/gethomepage/homepage/assets/4954274/653e43b7-c54e-48af-8bbc-c9379fcf5374)
![Bildschirmfoto 2023-12-16 um 10 26 36](https://github.com/gethomepage/homepage/assets/4954274/7e5fc74d-51cd-4dbf-bef9-3a9be9b1982f)

---

- `res.status(500).json({ error });`:
![Bildschirmfoto 2023-12-16 um 10 25 28](https://github.com/gethomepage/homepage/assets/4954274/c4643318-a1a1-416e-938c-0dc61070f7b7)
![Bildschirmfoto 2023-12-16 um 10 26 17](https://github.com/gethomepage/homepage/assets/4954274/5ac0f0ef-6203-4f54-b4e0-0b3b24f09b95)

2023-12-16 09:34 UTC, evorg commented
> [...] but rather than having 4 different implementations floating around... =)
> 
> LMK if you have any concerns

I thought about the same thing, but then didn't know where it would belong. Great!