Added Option for Grafana Alertmanager
gethomepage/homepage pull request #2498
Opened 2023-12-19 16:27 UTC by myztillx

## Proposed change

Added alertsmanager to grafana widget since the api used by `alerts` is deprecated (https://grafana.com/docs/grafana/latest/developers/http_api/alerting/). This change would put the number of blocks over 4, but only `alerts` or `alertmanager` will work, not both.

This is also not a feature request that had more than 5 upvotes, but does address a broken integration if using the new grafana alerts manager.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2023-12-19 16:42 UTC, myztillx commented
My understanding is that while the api will return a 200 response, it will just return an empty array. At least that is what happens whenever I have tried to get the `alerts` to work. So, it is correct to say that both will "work" in that regard, but useful data will not be returned. 

It also appears that starting with grafana 9, alerting is handed via the alertmanager. The use of the alerts api must be opted into. (https://grafana.com/docs/grafana/latest/alerting/set-up/migrating-alerts/). I believe a user who has gone through all these steps will know which one they are using (alerts or alertmanager).

Removal will occur in grafana 11 ([source](https://grafana.com/docs/grafana/latest/developers/http_api/alerting/))

I am open to alternatives if there is a way to have an either/or option. I did not investigate the code a lot to see if this was an option.

2023-12-19 16:56 UTC, shamoon commented
Yea so what I want to make sure is if it’s returning status 200 and an array (even if it’s empty) that the user still sees 4 blocks, working as expected.

similarly for users on older versions the new api call will fail, won’t it? So that would appear as an error for them.

Basically want to avoid this being functionally a breaking change (I realize it is in grafana but ideally we handle here gracefully)

I have to see how annoying it is to spin up a grafana instance to test, I don’t use it any more

2023-12-19 19:03 UTC, myztillx commented
Understandable, I was going with the idea that the user would know which fields they were using and would chose those options. I was not thinking of when no fields have been chosen it would show all 5. 

I want to avoid making this a "breaking" change as you say. The best way I can think of would be to do both queries and if the `alerts` query returns an empty array or error (non 200 response or otherwise), then try the `alertmanager` query. This way, it is hidden from the user at this time and should not result in breaking anything. I will test this out shortly if this seems feasible to you?

2023-12-19 19:34 UTC, shamoon commented
Yes I think something like that would make sense. It’ll be slightly more complicated logic than i wish to account for all the cases, but I think worth it in terms of making things seamless for the homepage user. We’ve had similar breaking changes in an API like this in the past, for example https://github.com/gethomepage/homepage/pull/2284/files but in that case the API gave us version info to use, not sure if we have anything like that here or it’ll be sorta trial-and-error like you said.

LMK when you’re happy with it and I can take a look

2023-12-19 19:44 UTC, myztillx commented
So after version 11, we could use that. Version 11 could be checked for and to use the `alertmanager` in that case. But with the old api being opt-in for now, I do not think there is a way to detect which alerts the user is using (at least not based on version).

2023-12-19 19:47 UTC, myztillx commented on src/widgets/grafana/component.jsx
> +  if (!statsData || (!alertsData && !alertmanagerData)) {
Need to check these as an and condition to prevent breaking when api is finally deprecated.

2023-12-19 19:47 UTC, myztillx commented on src/widgets/grafana/component.jsx
> +  if ((alertsError && alertsError.message === "HTTP Error") || !alertsData || alertsData.length === 0) {
How I see the flow working is checking for alertsError and the message "HTTP Error". This should occur when the api is finally removed in grafana 11. The second checks to see if any data was returned. And finally check if the returned data has length.

2023-12-19 22:34 UTC, shamoon commented on src/widgets/grafana/component.jsx
> +  if ((alertsError && alertsError.message === "HTTP Error") || !alertsData || alertsData.length === 0) {
Hmm, I would probably use the status code not a message, though in either case Im not certain what they will be, maybe we can figure that out.

But in general I think this would be OK. I guess the alternative is https://grafana.com/docs/grafana/latest/developers/http_api/other/#returns-health-information-about-grafana but that wont save us from the extra API call (in fact would add one, of course).

Have you had a chance to test this?

2023-12-20 21:35 UTC, myztillx commented
I was trying to, but it is fairly nested in the error message and I wasn't
sure how reliable it was to always be returned in that format.

I have tried this patch on my machine and it works for me, but I have the
newer alert manager setup and not the old alerts. Was hoping someone with
alerts setup would be able to test as well.

On Tue, Dec 19, 2023, 5:34 PM shamoon ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/widgets/grafana/component.jsx
> <https://github.com/gethomepage/homepage/pull/2498#discussion_r1432001747>
> :
>
> >
> -  if (statsError || alertsError) {
> +  let alertsInt = 0;
> +
> +  if ((alertsError && alertsError.message === "HTTP Error") || !alertsData || alertsData.length === 0) {
>
> Hmm, I would probably use the status code not a message, though in either
> case Im not certain what they will be, maybe we can figure that out.
>
> But in general I think this would be OK. I guess the alternative is
> https://grafana.com/docs/grafana/latest/developers/http_api/other/#returns-health-information-about-grafana
> but that wont save us from the extra API call (in fact would add one, of
> course).
>
> Have you had a chance to test this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gethomepage/homepage/pull/2498#discussion_r1432001747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIBLCUUI2M557OQWE22QWZLYKIJATAVCNFSM6AAAAABA3ONKWCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBZHAYTEMZVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-21 05:27 UTC, shamoon requested changes
<img width="782" alt="Screenshot 2023-12-20 at 9 24 02 PM" src="https://github.com/gethomepage/homepage/assets/4887959/6c35bfe3-c20d-4416-bf33-9d889e398111">
<img width="765" alt="Screenshot 2023-12-20 at 9 11 04 PM" src="https://github.com/gethomepage/homepage/assets/4887959/c8204784-4887-4d43-a696-ce7c501607e5">

Tested this with v8 and v9 and seems to be OK. See the one suggestion, LMK thoughts of course

2023-12-21 05:27 UTC, shamoon commented on src/widgets/grafana/component.jsx
> +  if ((alertsError && alertsError.message === "HTTP Error") || !alertsData || alertsData.length === 0) {
```suggestion
  if (alertsError || !alertsData || alertsData.length === 0) {
```

It should just be enough to check for the error. If the entire Grafana instance is down then everything should error out, so this wont be a problem and the later conditional will catch it

2023-12-27 04:21 UTC, shamoon approved these changes

2023-12-27 04:21 UTC, merged