Feature: search suggestions in quick launch
gethomepage/homepage pull request #2775
Opened 2024-01-27 21:54 UTC by Flo2410

## Proposed change

This PR adds search suggestions to the quick launch menu. 
Currently, only the top four suggestions are shown, but it could be made adjustable in the config. I just wasn't sure where to put the setting. To the quick launch setting or the search widget?

### Screenshot
![image](https://github.com/gethomepage/homepage/assets/31217036/b9f4c4be-b8a1-4a7d-9514-16649267ae9e)

### Config
I added an option to the `quicklaunch` setting called `hideSearchSuggestions` which hides the suggestions. 
Furthermore, I added the option `suggestionUrl` to the custom search widget. 
This allows the user to set a custom URL for suggestions, like this:

```yaml
- search:
    provider: custom
    url: https://www.ecosia.org/search?q=
    suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
    target: _blank
```

The body of the response from the API configured with  `suggestionUrl` should have the following format:

```json
[
  "home",
  [
    "home depot",
    "home depot near me",
    "home equity loan",
    "homeworkify",
    "homedepot.com",
    "homebase login",
    "home depot credit card",
    "home goods"
  ]
]
```

> The first entry of the array contains the search query, the second one is an array of the suggestions.
> In the example above, the search query was **home**.

The above example is also included in the change to the docs.

I found suggestion URLs for all implemented search providers and *Ecosia* which I used as an example for the custom provider.

Relates to #1225 and #1517

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-01-27 22:05 UTC, shamoon requested changes
Thanks. I can take a look at the PR later but this should be opt-in not opt-out, otherwise we’re going to get a lot of complaints about this showing up out of nowhere.

in that case presumably the variable should be renamed to `show…`

Also FYI our guidelines now require 10 up-votes for new features but I realize the docs don’t show that for the latest version yet

2024-01-27 23:55 UTC, shamoon commented
Sorry I just noticed that the feature guidelines were in fact published before the PR was opened. In the interest of applying the rules equally (we get complaints otherwise) I’m going to close this but I’ll be more than happy to re-address when the requirement is met. I hope your understand, thank you for the PR

2024-01-28 00:30 UTC, shamoon commented
Sorry for the craziness, this closes two FRs so let’s call it > 10 :)

2024-01-28 01:12 UTC, shamoon requested changes
It's also a bit odd that this works only for quick launch but comes from search. I think it should be implemented for both so they mirror each other. We'll need to make sure the UI for the search one is good.

2024-01-28 01:12 UTC, shamoon commented on src/components/quicklaunch.jsx
> +                name: suggestion,
```suggestion
                name: `${searchProvider.name ?? t("quicklaunch.custom")} ${t("quicklaunch.search")}: ${suggestion}`,
```

Im curious what you think about this one. I think it might be better to have the name of the search in the line to make it more explicit, it's obviously visually a bit more cluttered but I think it helps when e.g. theres also a service in the list.

I think actually even better would be to add a new quick launch "type", something like "searchSuggestion" and then that could be slightly visually differentiated like smaller or gray text or something like that

Again, curious your thoughts

<img width="793" alt="Screenshot 2024-01-27 at 5 02 04 PM" src="https://github.com/gethomepage/homepage/assets/4887959/bb2dff6b-58cd-4740-a28d-9101c2719393">

2024-01-28 01:12 UTC, shamoon commented on src/components/widgets/search/search.jsx
> +    suggestionUrl: false,
```suggestion
```

2024-01-28 01:12 UTC, shamoon commented on src/pages/index.jsx
> +        },
```suggestion
        name: "Custom",
        url: searchWidget.options.url,
        suggestionUrl: searchWidget.options.suggestionUrl,
```

2024-01-28 20:45 UTC, Flo2410 commented on src/components/quicklaunch.jsx
> +                name: suggestion,
That's a good question and probably depends on personal preferences. 

I don't like how it looks with the `Google Search:` in front of the suggestions. I find it difficult to quickly see the suggestion, always having to scan the line for the colon/start of the suggestion.

I have two ideas myself down below.

![image](https://github.com/gethomepage/homepage/assets/31217036/09442d5f-70e8-473a-a79c-91c3faeaaf5e)

## Idea 1

Showing the icon of the search provider would be an easy way of indicating that it is a search and which provider is used. Ideally, the icon would be the same as the one used in the search bar. For that to work, the `ResolvedIcon` component would need to allow `react-icons` icons to be passed in as an icon. Alternatively, the search bar could use the current version of `ResolvedIcon` and the `searchProviders` object would store the SI icon string instead of the component from `react-icons`. I did not test these yet, for the images below I just hard-coded the string for the `icon` property. 

The result would look like this:

![image](https://github.com/gethomepage/homepage/assets/31217036/113f11bb-0097-4789-bed3-5f17cdc36447)

## Idea 2

My second idea would include your suggestion of creating a new "type" for the search suggestions. 
With that, we could show the suggestion part of the search query with a lower opacity or a darker color (for the example below, I used `opacity-50`).

I must say, I really like how it looks. It's super easy to see the suggestions, and it's clear which provider they use. 

![image](https://github.com/gethomepage/homepage/assets/31217036/693b1b3f-8d13-450e-9d30-7fe32b41ecc0)

2024-01-28 21:08 UTC, Flo2410 commented on src/pages/index.jsx
> +        },
I'm curious about that one. Why wouldn't you copy the custom search provider from the `searchProviders` object when it is done for all others? 
Furthermore, shouldn't the `name` property be `undefined` for the custom provider?
The `custom` name is resolved here (as I understand it): https://github.com/gethomepage/homepage/blob/d20cdbb9ab1432e69ce68c9b4255aef9eac52ff4/src/components/quicklaunch.jsx#L112

Moreover, if we are going to show the icon, the icon for the custom provider would need to be set here as well. Or we get it from the `searchProviders`

So if I didn't overthink something, it should look like this:
```js
searchProvider = {
  url: searchWidget.options.url,
  suggestionUrl: searchWidget.options.suggestionUrl,
  icon: searchProviders.custom.icon // only if we show the icon of the prvider as suggested above
};
```

2024-01-28 21:57 UTC, Flo2410 commented
Regrading the search in the search bar: 

I made a quick implementation using the `Combobox` from `headlessui`. 
It obviously still needs some work, but I would like some guidance regarding the design of the dropdown. 

![image](https://github.com/gethomepage/homepage/assets/31217036/c875d881-ade0-4048-84e6-cb1db73f3324)

Furthermore, I would suggest moving the settings for the search provider, including the `showSearchSuggestions` setting, into a [provider](https://gethomepage.dev/main/configs/settings/#providers) in the future. This probably would also enable the search function in the quick launch to work without having the search widget enabled. But this most likely falls out of the scope of this PR.

2024-01-29 00:37 UTC, shamoon reviewed
Thanks for changes.

Yea the search widget auto-complete is a good start. As far as the design, it'd be easier if you push those changes and I can play with it, if youre OK with that.

And yea, maybe it seems overkill but users generally want more control especially as this is sending data (and getting tracked, of course) so I would include a setting for the widget (showSuggestions) in addition to the quick launch one. And I think something even better would be what we've done similarly elsewhere which is to let the search widget one act as the 'default' for quick launch (in other words if you set search widget `showSuggestions` to true, the quick launch will do the same unless you explicitly set it to false). If you only want them in quick launch set it just in quick launch. That feels 'clean' and means a lot of users will only need to set it in one place (if you want suggestions in search widget theres a good chance you do in QL).

2024-01-29 00:37 UTC, shamoon commented on src/pages/index.jsx
> +        },
Yea all I was trying to say here was that `{ ...{ url: ... } }` is just a weird way of writing `{ url: ... }`, I didnt really double-check the specific properties are what we want

2024-01-29 00:37 UTC, shamoon commented on src/components/quicklaunch.jsx
> +                name: suggestion,
Yea, idea 2 is exactly the kind of thing I had in mind, agree it looks great.

I'm not sure about the icon but Im also sorta tempted to leave it for another PR, keep this one focused?

2024-01-29 00:40 UTC, shamoon commented on docs/widgets/info/search.md
> +The response body for the URL provided with the `suggestionUrl` option should looke like this:
```suggestion
The response body for the URL provided with the `suggestionUrl` option should look like this:
```

2024-01-29 20:27 UTC, Flo2410 commented
I pushed the draft for the suggestions in the search bar.
You can activate them by adding `showSearchSuggestions: true` to the search widget config.

2024-01-29 20:34 UTC, Flo2410 commented on src/pages/index.jsx
> +        },
I've fixed it in 5f0924d9328cda79d118a630ff8916e372c62964

2024-01-29 21:09 UTC, Flo2410 commented on src/components/quicklaunch.jsx
> +                name: suggestion,
I added it without the image in ed827837aa86a892fd7603e6d0dc8187138f58c2

It looks like this:
![image](https://github.com/gethomepage/homepage/assets/31217036/4f6acf0f-e52f-4d4f-8c88-a97e74af7775)

2024-01-29 21:44 UTC, shamoon commented
Cool thanks! I think something happened with the custom provider for search widget, I'll take a look at all of it as soon as I can find a minute

2024-01-30 18:58 UTC, Flo2410 reviewed
The search provider setting is still broken... 
I'm not sure what a good solution would be.

2024-01-30 18:58 UTC, Flo2410 commented on src/components/quicklaunch.jsx
> +    settings?.quicklaunch?.showSearchSuggestions ?? searchProvider.showSearchSuggestions
This does not work as expected, as `searchProvider.showSearchSuggestions` is only set for the `custom` search provider. This is because for the custom provider the `searchProvider` gets set to the options, but the predefined ones get set from the `searchProviders` object in `search.jsx`.

2024-01-30 18:58 UTC, Flo2410 commented on src/pages/index.jsx
> +      searchProvider = searchWidget.options;
I am not sure what to do here exactly, but currently the `searchProvider` object looks different for the `custom' and predefined providers.

As the problem is above, the predefined one is missing the `showSearchSuggestions` option and the custom one has no `name` (the quick launch is relying on that for showing the `t("quicklaunch.custom")`) https://github.com/gethomepage/homepage/blob/ef257565344f6c1db818609b94e01eec28993b31/src/components/quicklaunch.jsx#L118

custom provider:
```json
"index": 1,
"provider": "custom",
"showSearchSuggestions": true,
"suggestionUrl": "https://ac.ecosia.org/autocomplete?type=list&q=",
"target":  "_blank",
"url":  "https://www.ecosia.org/search?q="
```

predefined provider:
```json
"icon": SiGoogle,
"name": "Google",
"suggestionUrl": "https://www.google.com/complete/search?client=chrome&q=",
"url": "https://www.google.com/search?q="
```

2024-01-30 19:01 UTC, Flo2410 commented
I also found a bug with the greying out of the suggestions.
I will fix this and would also implement it for the search bar suggestions.

![image](https://github.com/gethomepage/homepage/assets/31217036/81ecaf88-fea6-4ffb-bc5b-eb668556cf56)

2024-01-30 19:02 UTC, shamoon commented on src/components/quicklaunch.jsx
> +    settings?.quicklaunch?.showSearchSuggestions ?? searchProvider.showSearchSuggestions
Oh good point, I'll take a look

2024-01-30 19:14 UTC, shamoon commented
Great catch about the non-custom providers, I think should be sorted but lmk

2024-01-30 19:19 UTC, shamoon commented on src/components/quicklaunch.jsx
> +                                {r.name.substring(searchString.length)}
```suggestion
                              <span className="whitespace-pre">{r.name.indexOf(searchString) === 0 ? searchString : ''}</span>
                              <span className="mr-4 whitespace-pre opacity-50">
                                {r.name.indexOf(searchString) === 0 ? r.name.substring(searchString.length) : r.name}
```

I think something simple like this would do it, but realize you may be working on it

<img width="686" alt="Screenshot 2024-01-30 at 11 18 09 AM" src="https://github.com/gethomepage/homepage/assets/4887959/f7b6b0c9-2e81-463b-8e27-c0ab2e442646">
<img width="676" alt="Screenshot 2024-01-30 at 11 18 19 AM" src="https://github.com/gethomepage/homepage/assets/4887959/93a7b37c-1f17-42ca-b6de-57578d905615">

2024-01-30 19:38 UTC, shamoon commented on src/components/quicklaunch.jsx
> +                                {r.name.substring(searchString.length)}
Just playing with them a bit aren't the suggestions always going to be at the beginning of the string if its in the suggestion at all?

2024-01-30 19:39 UTC, Flo2410 commented on src/components/quicklaunch.jsx
> +                                {r.name.substring(searchString.length)}
No, unfortunately not.

 See the `http://gmx.at`

2024-01-30 20:28 UTC, Flo2410 commented on src/components/quicklaunch.jsx
> +                                {r.name.substring(searchString.length)}
Okay, I gave up on trying my idea...

I would probably implement your first idea because with your second one, if you spell the search wrong, everything full opacity. I think it looks better all with reduced opacity in that case, because nothing is actually matching the input.

![image](https://github.com/gethomepage/homepage/assets/31217036/7230b0e0-ad2b-43b2-b7f6-33fd32e1c973)

![image](https://github.com/gethomepage/homepage/assets/31217036/57143a6f-cc9f-4bd5-bdd1-ed6db14cc774)

2024-01-30 20:32 UTC, shamoon commented on src/components/quicklaunch.jsx
> +                                {r.name.substring(searchString.length)}
Ok yea Im good with that.

2024-01-30 20:57 UTC, Flo2410 commented
I think we are good here.
The only thing that bothers me is that the Google API doesn't return UTF-8 strings.

2024-01-30 21:38 UTC, Flo2410 commented
I couldn't live with it. Looks like Google only returns UTF-8 if the User Agent includes `Mozilla/5.0`.

2024-01-30 23:51 UTC, shamoon commented on src/utils/proxy/cached-fetch.js
Oh. What does this actually fix? I'd prefer we not touch this, just in the tiny possibility of unintended consequences and all.

2024-01-31 18:30 UTC, Flo2410 commented on src/utils/proxy/cached-fetch.js
This sets the `User-Agent`  to a value recognized by the Google search suggestion API so that it returns the response UTF-8 encoded. The default user agent for node.js is `undici` or as of some 21.x.x version `node`.
I suspect that the change would only improve compatibility, but I can understand your perspective. So, maybe it could be investigated and changed in a future PR.

With the `User-Agent` header:
![image](https://github.com/gethomepage/homepage/assets/31217036/0c36e742-1f3c-4998-b18f-fb0069273a6d)

Without the header:
![image](https://github.com/gethomepage/homepage/assets/31217036/ada25032-7249-42c6-b3e7-74e24c8d163f)

Also, the API gets spammed with this because *�* doesn't match *ü*

2024-01-31 18:35 UTC, Flo2410 commented
While writing the response above, I found some more bugs:

The first one is the Z-Index of the quick launch not being high enough:

![image](https://github.com/gethomepage/homepage/assets/31217036/d27b6e5f-a8cf-4ee1-b7f5-93621fff00da)

The second one are unexpected line breaks because of the `span` elements for the suggestions.

![image](https://github.com/gethomepage/homepage/assets/31217036/1b4a7c8d-76ea-4037-8f82-a4188747f61b)

The window width was 620px for the second screenshot.

2024-01-31 18:46 UTC, shamoon commented
Thanks great catches! Should be fixed and I reverted the UA thing. Agree we can address in the future if needed, you ok with that?

2024-01-31 20:47 UTC, Flo2410 commented
I found another bug, I didn't URI encode the query again in the API route. This made it so that special characters were not correctly sent to the search suggestions API. 

But apart from that, I think we are fine.

The thing with the Umlaut for Google doesn't bother me too much (I use DuckDuckGo anyway ;) ) 

While testing the Umlaut thing, I found another bug, but I will open an issue for that one.

2024-01-31 22:43 UTC, shamoon commented
> How do I report a Bug?

You can open a discussion about it.

2024-02-01 01:17 UTC, shamoon approved these changes
Great work

2024-02-01 01:17 UTC, merged