Feat: OpenWRT widget implementation
gethomepage/homepage pull request #2782
Opened 2024-01-29 18:05 UTC by DanGRT

## Proposed change

Adds a widget for OpenWRT integration
<img width="838" alt="Screenshot 2024-01-29 at 17 54 49" src="https://github.com/gethomepage/homepage/assets/38405106/017ec904-1493-4e26-90ff-c559598ff78f">

Allows for either system info or information on a particular interface (i.e eth0 for WAN) by adding that interface name as `interfaceName` in services.yaml

Closes #1509

## Type of change

Adds a new widget for OpenWRT

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x]  If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-01-29 18:06 UTC, DanGRT commented
I'm not 100% on the statistics shown here, though the OpenWRT rpc schema is a little tricky to work with so thought of this as decent enough start. Please let me know if you have any suggestions or any requirements I have missed. Thanks

2024-01-29 18:12 UTC, shamoon commented
Please provide some sample data, thanks

2024-01-29 18:57 UTC, DanGRT commented
Not sure if this is what you want exactly, let me know if not.

Example `services.yaml`:
```
- OpenWRT:
    - System:
        href: http://192.168.1.71
        widget:
          type: openwrt
          url: http://192.168.1.71
          username: homepage-widget
          password: 1234
    - WAN:
        href: http://192.168.1.71
        widget:
          type: openwrt
          url: http://192.168.1.71
          username: homepage-widget
          password: 1234
          interfaceName: eth0
    - LAN:
        href: http://192.168.1.71
        widget:
          type: openwrt
          url: http://192.168.1.71
          username: homepage-widget
          password: 1234
          interfaceName: eth1
```

Example response data for `["system", "info", {}]`

```[
   0,
   {
      "localtime":1706553900,
      "uptime":939985,
      "load":[
         3264,
         5664,
         4736
      ],
      "memory":{
         "total":8181571584,
         "free":292585472,
         "shared":27353088,
         "buffered":209911808,
         "available":531288064,
         "cached":4923392
      },
      "root":{
         "total":4046560,
         "free":4023408,
         "used":23152,
         "avail":3797312
      },
      "tmp":{
         "total":3994908,
         "free":3993860,
         "used":1048,
         "avail":3993860
      },
      "swap":{
         "total":8178888704,
         "free":6991638528
      }
   }
]```

Example response data for `["network.device", "status", {}]`

```[
   0,
   {
      "eth0":{
         "external":false,
         "present":true,
         "type":"Network device",
         "up":true,
         "carrier":true,
         "auth_status":false,
         "link-advertising":[
            
         ],
         "link-partner-advertising":[
            
         ],
         "link-supported":[
            
         ],
         "speed":"10000F",
         "autoneg":false,
         "flow-control":{
            "autoneg":true,
            "supported":[
               
            ],
            "link-advertising":[
               
            ],
            "link-partner-advertising":[
               
            ],
            "negotiated":[
               
            ]
         },
         "hw-tc-offload":false,
         "devtype":"ethernet",
         "mtu":1500,
         "mtu6":1500,
         "macaddr":"br:24:11:1t:4f:99",
         "txqueuelen":1000,
         "ipv6":true,
         "ip6segmentrouting":false,
         "promisc":false,
         "rpfilter":0,
         "acceptlocal":false,
         "igmpversion":0,
         "mldversion":0,
         "neigh4reachabletime":30000,
         "neigh6reachabletime":30000,
         "neigh4gcstaletime":60,
         "neigh6gcstaletime":60,
         "neigh4locktime":100,
         "dadtransmits":1,
         "multicast":true,
         "sendredirects":true,
         "drop_v4_unicast_in_l2_multicast":false,
         "drop_v6_unicast_in_l2_multicast":false,
         "drop_gratuitous_arp":false,
         "drop_unsolicited_na":false,
         "arp_accept":false,
         "gro":false,
         "statistics":{
            "collisions":0,
            "rx_frame_errors":0,
            "tx_compressed":0,
            "multicast":0,
            "rx_length_errors":0,
            "tx_dropped":0,
            "rx_bytes":26907591560,
            "rx_missed_errors":0,
            "tx_errors":0,
            "rx_compressed":0,
            "rx_over_errors":0,
            "tx_fifo_errors":0,
            "rx_crc_errors":0,
            "rx_packets":21897182,
            "tx_heartbeat_errors":0,
            "rx_dropped":0,
            "tx_aborted_errors":0,
            "tx_packets":12526904,
            "rx_errors":0,
            "tx_bytes":5315404801,
            "tx_window_errors":0,
            "rx_fifo_errors":0,
            "tx_carrier_errors":0
         }
      },
      "eth1":{
         "external":false,
         "present":true,
         "type":"Network device",
         "up":false,
         "carrier":true,
         "auth_status":false,
         "link-advertising":[
            
         ],
         "link-partner-advertising":[
            
         ],
         "link-supported":[
            
         ],
         "speed":"10000F",
         "autoneg":false,
         "flow-control":{
            "autoneg":true,
            "supported":[
               
            ],
            "link-advertising":[
               
            ],
            "link-partner-advertising":[
               
            ],
            "negotiated":[
               
            ]
         },
         "hw-tc-offload":false,
         "devtype":"ethernet",
         "mtu":1500,
         "mtu6":1500,
         "macaddr":"bd:24:11:eb:67:25",
         "txqueuelen":1000,
         "ipv6":true,
         "ip6segmentrouting":false,
         "promisc":false,
         "rpfilter":0,
         "acceptlocal":false,
         "igmpversion":0,
         "mldversion":0,
         "neigh4reachabletime":30000,
         "neigh6reachabletime":30000,
         "neigh4gcstaletime":60,
         "neigh6gcstaletime":60,
         "neigh4locktime":100,
         "dadtransmits":1,
         "multicast":true,
         "sendredirects":true,
         "drop_v4_unicast_in_l2_multicast":false,
         "drop_v6_unicast_in_l2_multicast":false,
         "drop_gratuitous_arp":false,
         "drop_unsolicited_na":false,
         "arp_accept":false,
         "gro":false,
         "statistics":{
            "collisions":0,
            "rx_frame_errors":0,
            "tx_compressed":0,
            "multicast":0,
            "rx_length_errors":0,
            "tx_dropped":0,
            "rx_bytes":4701031034,
            "rx_missed_errors":0,
            "tx_errors":0,
            "rx_compressed":0,
            "rx_over_errors":0,
            "tx_fifo_errors":0,
            "rx_crc_errors":0,
            "rx_packets":11637883,
            "tx_heartbeat_errors":0,
            "rx_dropped":0,
            "tx_aborted_errors":0,
            "tx_packets":21399834,
            "rx_errors":0,
            "tx_bytes":25783880880,
            "tx_window_errors":0,
            "rx_fifo_errors":0,
            "tx_carrier_errors":0
         }
      }
   }
]```

Example from `["00000000000000000000000000000000", "session", "login"]`:

  ```[0,{"ubus_rpc_session":"1234","timeout":300,"expires":300,"acls": {}}]```

2024-01-29 19:02 UTC, DanGRT commented
Yeah, basically when first logging in you need to provide a ubus_rpc_session as the first element in params array (just as when you're logged in) 

> The session id 00000000000000000000000000000000 (32 zeros) is a special null-session which only has the rights from the unauthenticated access group, only enabling the session.login ubus call. A session has a timeout that can be specified when you login, otherwise it defaults to 5 minutes.
https://openwrt.org/docs/techref/ubus#session_management

2024-01-29 19:30 UTC, shamoon requested changes
Thanks, some small notes.

I cant really test the proxy, of course, will take your word for it on that. Hopefully openwrt is pretty consistent across installs...

<img width="736" alt="Screenshot 2024-01-29 at 11 26 57 AM" src="https://github.com/gethomepage/homepage/assets/4887959/53af22f0-f7d3-4bcb-8861-e7550ec968cb">
<img width="739" alt="Screenshot 2024-01-29 at 11 26 53 AM" src="https://github.com/gethomepage/homepage/assets/4887959/7870b048-d6df-4ce0-b4c1-366de5c68fd9">

2024-01-29 19:30 UTC, shamoon commented on docs/widgets/services/openwrt.md
> +Adding an interfaceName (e.g eth0) will display information for that particular device, otherwise it will display general system info.
```suggestion
Setting `interfaceName` (e.g. eth0) will display information for that particular device, otherwise the widget will display general system info.
```

2024-01-29 19:30 UTC, shamoon commented on src/widgets/openwrt/proxy.js
> +    [status, contentType, data] = await fetchData(url, widget);
```suggestion
    [status, , data] = await fetchData(url, widget);
```

2024-01-29 19:30 UTC, shamoon commented on src/widgets/openwrt/proxy.js
> +    const [loginStatus, loginContentType, loginData] = await login(url, widget.username, widget.password);
```suggestion
    const [loginStatus, , loginData] = await login(url, widget.username, widget.password);
```

2024-01-29 19:30 UTC, shamoon commented on src/widgets/openwrt/proxy.js
> +  const [_status, contentType, data] = await sendJsonRpcRequest(url, RPC_METHOD, [authToken, ...PARAMS.system]);
```suggestion
  const [, contentType, data] = await sendJsonRpcRequest(url, RPC_METHOD, [authToken, ...PARAMS.system]);
```

2024-01-29 19:30 UTC, shamoon commented on src/widgets/openwrt/proxy.js
> +  let [status, contentType, data] = await fetchData(url, widget);
```suggestion
  let [status, , data] = await fetchData(url, widget);
```

2024-01-29 19:30 UTC, shamoon commented on src/widgets/openwrt/proxy.js
> +  const [_status, contentType, data] = await sendJsonRpcRequest(url, RPC_METHOD, [authToken, ...PARAMS.device]);
```suggestion
  const [, contentType, data] = await sendJsonRpcRequest(url, RPC_METHOD, [authToken, ...PARAMS.device]);
```

2024-01-29 19:30 UTC, shamoon commented on public/locales/en/common.json
> +        "cpuLoad": "CPU Load Avg (5 mins)",
```suggestion
        "cpuLoad": "CPU Load Avg",
```

Or at most `(5m)`
people complain a lot about long labels around here =)

2024-01-29 19:30 UTC, shamoon commented on public/locales/en/common.json
> +        "uptimeValue": "{{days}}d {{hours}}h {{minutes}}m {{seconds}}s",
```suggestion
```

2024-01-29 19:30 UTC, shamoon commented on src/widgets/openwrt/methods/system.jsx
> +        })}
```suggestion
        value={t("common.uptime", { value: uptime })}
```

we have a formatter for this

2024-01-29 19:30 UTC, shamoon commented on docs/widgets/services/openwrt.md
> +  interfaceName: eth0
```suggestion
  interfaceName: eth0 # optional
```

2024-01-29 19:30 UTC, shamoon commented on public/locales/en/common.json
> +        "down": "DOWN",
```suggestion
        "up": "Up",
        "down": "Down",
```

2024-01-29 19:37 UTC, shamoon commented
Ah, sorry my bad I did not mean to actually push that changes (I had them just to test the lint).

2024-01-29 20:00 UTC, DanGRT commented on src/widgets/openwrt/methods/system.jsx
> +        })}
oh awesome

2024-01-29 20:11 UTC, DanGRT commented on public/locales/en/common.json
> +        "cpuLoad": "CPU Load Avg (5 mins)",
I stuck to `(5m)`, openwrt returns 3 values so I'd prefer to note which one if possible

2024-01-29 20:14 UTC, DanGRT commented
> Ah, sorry my bad I did not mean to actually push that changes (I had them just to test the lint).

All good~ I've pushed up with your suggestions. Only one I differed on was using `(5m)`, just because load is returned as an array of 3 values from openwrt (1, 5 and 15 minutes) so I'd prefer to label it as such. Let me know if theres anything else.

Thanks!

2024-01-29 20:33 UTC, shamoon approved these changes
Great thanks

2024-01-29 20:33 UTC, merged

2024-01-29 20:36 UTC, DanGRT commented
Thanks shamoon

2024-02-19 07:10 UTC, gasment commented
I tried using and found some issues（with my sys env）：
1.lt work with uhttpd & uhttpd-mod-ubus，i can not make it work with nginx & nginx-mod-bus；
2.
 I use the following services.yaml config sample，It can respond system uptime and CPU load，but not work with interfaceName（browser respond a err:Unauthorized，Command Line show ”Access denied”）
​  
```
widget:
          type: openwrt
          url: http://192.168.1.71
          username: homepage-widget
          password: 1234
```
3.i do some research，lt may related to the rpc acl，so i add a acl profile like this:
/usr/share/rpcd/acl.d/network.device.json
```
{
        "network.device": {
                "description": "Access controls for network device",
                "read": {
                        "ubus": {
                                "network.device": ["status"]
                        }
                }
        }
}
```
restart the rpcd service ,now i can normally get the interface info in homepage widget

thanks to make this widget，I've been waiting for this for a long time

2024-02-23 18:50 UTC, shamoon commented
Better to start a new discussion than comment on a closed PR. Also please post the container logs and api output (there) for that