Bugfixes for search suggestions
gethomepage/homepage pull request #2867
Opened 2024-02-08 21:08 UTC by Flo2410

## Proposed change

This PR fixes two bugs with the search suggestion.

- The search box opened the search URL when loosing focus.
- The suggestion API kept getting called without the search changing.

Closes #2866 

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [ ] If applicable, I have added corresponding documentation changes.
- [ ] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-02-08 21:16 UTC, shamoon requested changes
Thanks for finding / working on these.

-  I still see the focus bug if you tab out of the search widget
- I cant recreate the other one, not sure exactly what conditions are needed. Anyway, that change seems fine.

2024-02-08 21:17 UTC, shamoon commented
Oh, perhaps the other PR will fix the tab thing.

2024-02-08 21:21 UTC, shamoon commented
Gotcha. Please put the tab fix here, the other one is a feature and to be fair I think it should meet the usual requirements. Sorry for the confusion.

2024-02-08 21:50 UTC, Flo2410 commented
I've added the fix for the Tab issue.

2024-02-08 21:54 UTC, shamoon requested changes

2024-02-08 21:54 UTC, shamoon commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Im on my phone (so cant test right this second) but wont this also prevent actually tabbing out of the field?

2024-02-08 21:58 UTC, Flo2410 commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Yes, it does.  I'll try to fix that.

FYI: The reason the *tab* key submits the search is the [headlessui combobox](https://headlessui.com/react/combobox#keyboard-interaction)

2024-02-08 22:00 UTC, shamoon commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Yea I figured it came from that, might be annoying to figure out a workaround if they dont provide an easy way

2024-02-08 22:18 UTC, Flo2410 commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Fixed it. Now the *Tab* is on disabled if the suggestion dropdown is open (it can be closed with *escape*).

2024-02-08 22:28 UTC, shamoon commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Hmm, but this has the same issue, no? If the user wants to tab out of the field i.e. they have multiple search engines and they want to tab over to that dropdown, they'd have to hit esc first?

Maybe its the best we can do, I find the opening on Tab a weird thing but its listed under their accessibility notes, I'm not aware of that interaction...

2024-02-08 22:41 UTC, Flo2410 commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Maybe there should be a custom implementation of the combobox for the search widget. 

But for now, the search provider button gets manually focused if the dropdown is open.

2024-02-08 22:48 UTC, Flo2410 commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
Also, just remembered that the `useRef` hook exists. Therefore, I changed the `document.getElementById` calls to a ref with the `useRef` hook.

2024-02-08 22:54 UTC, shamoon commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
This feels like the wrong direction, we're just creating more and more specific cases. For example you cant tab backwards (shift tab) out of the field.

Perhaps just not using onChange at all and using our own handlers? We only want the search to open on click or enter key, after all...

I'll find some time to play with it and see, indeed maybe we cant do any better.

2024-02-09 08:25 UTC, shamoon commented on src/components/widgets/search/search.jsx
> +      event.preventDefault();
It's a little odd, but take a look at the last commit and let me know what you think. Still open to another solution, of course

2024-02-09 09:13 UTC, Flo2410 commented
Nice, that's much better. Thx.

2024-02-09 15:49 UTC, shamoon approved these changes
Great, thanks again for hunting these down

2024-02-09 15:49 UTC, merged