Add enablePools option to TrueNAS service widget
gethomepage/homepage pull request #2908
Opened 2024-02-14 21:57 UTC by dstotz

## Proposed change

- Maintain the previous behavior with previous configuration
- Add new optional parameter for `enablePools` that when enabled will display each Pool in the TrueNAS instance with its disk usage, and a status indicator

![image](https://github.com/gethomepage/homepage/assets/9381594/f0f6e805-82c8-4470-8cf4-4dfe0c89ba2b)

Closes #2792 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-02-15 02:45 UTC, shamoon requested changes
Also would be great if you can supply example api output

2024-02-15 02:45 UTC, shamoon commented on src/widgets/truenas/proxy.js
This proxy seems unnecessary, I need to check but I think you can just use credentialed

2024-02-15 02:45 UTC, shamoon commented on src/utils/proxy/handlers/credentialed.js
> +        body: req.body,
Again, needed?

2024-02-15 14:42 UTC, dstotz commented
> Also would be great if you can supply example api output

Sure, no problem! Do you wan the example as an inline comment somewhere in the code? Or just here on the PR for your reference? Here is a link to the API docs https://www.truenas.com/docs/api/scale_rest_api.html it is the `GET /pool` request

2024-02-15 14:42 UTC, dstotz commented on src/widgets/truenas/proxy.js
Agreed. I had just moved the previous request logic out of the existing `widget.js` to clean stuff up, but you are right we just don't need it at all.

Done.

2024-02-15 15:12 UTC, shamoon commented
> Sure, no problem! Do you wan the example as an inline comment somewhere in the code? Or just here on the PR for your reference? Here is a link to the API docs https://www.truenas.com/docs/api/scale_rest_api.html it is the `GET /pool` request

Just in a comment here for testing

![image](https://github.com/gethomepage/homepage/assets/4887959/4214bdb4-3f42-4987-9a06-ea6e30bb0924)

2024-02-15 19:40 UTC, shamoon commented
You re-requested review but didnt post API output, unless Im not seeing it?

2024-02-16 04:57 UTC, dstotz commented
> You re-requested review but didnt post API output, unless Im not seeing it?

Apologies, miscommunication. I had thought your screenshot indicated you found what you need by looking at the response schema. I'll include an output example below

```
[
    {
        "id": 3,
        "name": "AppData",
        "guid": "12345fakeguid67890",
        "encrypt": 0,
        "encryptkey": "",
        "path": "/mnt/AppData",
        "status": "ONLINE",
        "scan": {
            "function": "SCRUB",
            "state": "FINISHED",
            "start_time": {
                "$date": 1705816803000
            },
            "end_time": {
                "$date": 1705817857000
            },
            "percentage": 99.99964237213135,
            "bytes_to_process": 441097035776,
            "bytes_processed": 441098600448,
            "bytes_issued": 441097035776,
            "pause": null,
            "errors": 0,
            "total_secs_left": null
        },
        "topology": {
            "data": [
                {
                    "name": "mirror-0",
                    "type": "MIRROR",
                    "path": null,
                    "guid": "12345fakeguid67890",
                    "status": "ONLINE",
                    "stats": {
                        "timestamp": 129768022889925,
                        "read_errors": 0,
                        "write_errors": 0,
                        "checksum_errors": 0,
                        "ops": [
                            0,
                            478115,
                            7398499,
                            0,
                            0,
                            0,
                            0
                        ],
                        "bytes": [
                            0,
                            5816020992,
                            194377064448,
                            0,
                            0,
                            0,
                            0
                        ],
                        "size": 996432412672,
                        "allocated": 503696805888,
                        "fragmentation": 47,
                        "self_healed": 0,
                        "configured_ashift": 12,
                        "logical_ashift": 9,
                        "physical_ashift": 9
                    },
                    "children": [
                        {
                            "name": "fake-uuid-value-dummy-data",
                            "type": "DISK",
                            "path": "/dev/disk/by-partuuid/fake-uuid-value-dummy-data",
                            "guid": "12345fakeguid67890",
                            "status": "ONLINE",
                            "stats": {
                                "timestamp": 129768022939568,
                                "read_errors": 0,
                                "write_errors": 0,
                                "checksum_errors": 0,
                                "ops": [
                                    0,
                                    236984,
                                    3688201,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "bytes": [
                                    0,
                                    2854191104,
                                    97188532224,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "size": 0,
                                "allocated": 0,
                                "fragmentation": 0,
                                "self_healed": 0,
                                "configured_ashift": 12,
                                "logical_ashift": 9,
                                "physical_ashift": 9
                            },
                            "children": [],
                            "device": "sdi2",
                            "disk": "sdi",
                            "unavail_disk": null
                        },
                        {
                            "name": "fake-uuid-value-dummy-data",
                            "type": "DISK",
                            "path": "/dev/disk/by-partuuid/fake-uuid-value-dummy-data",
                            "guid": "12345fakeguid67890",
                            "status": "ONLINE",
                            "stats": {
                                "timestamp": 129768022968122,
                                "read_errors": 0,
                                "write_errors": 0,
                                "checksum_errors": 0,
                                "ops": [
                                    0,
                                    241131,
                                    3710298,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "bytes": [
                                    0,
                                    2961829888,
                                    97188532224,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "size": 0,
                                "allocated": 0,
                                "fragmentation": 0,
                                "self_healed": 0,
                                "configured_ashift": 12,
                                "logical_ashift": 9,
                                "physical_ashift": 9
                            },
                            "children": [],
                            "device": "sdh2",
                            "disk": "sdh",
                            "unavail_disk": null
                        }
                    ],
                    "unavail_disk": null
                }
            ],
            "log": [],
            "cache": [],
            "spare": [],
            "special": [],
            "dedup": []
        },
        "healthy": true,
        "warning": false,
        "status_detail": null,
        "size": 996432412672,
        "allocated": 503696805888,
        "free": 492735606784,
        "freeing": 0,
        "fragmentation": "47",
        "size_str": "996432412672",
        "allocated_str": "503696805888",
        "free_str": "492735606784",
        "freeing_str": "0",
        "autotrim": {
            "value": "off",
            "rawvalue": "off",
            "parsed": "off",
            "source": "DEFAULT"
        },
        "encryptkey_path": null,
        "is_decrypted": true
    },
    {
        "id": 4,
        "name": "Fun",
        "guid": "12345fakeguid67890",
        "encrypt": 0,
        "encryptkey": "",
        "path": "/mnt/Fun",
        "status": "ONLINE",
        "scan": {
            "function": "SCRUB",
            "state": "FINISHED",
            "start_time": {
                "$date": 1705816812000
            },
            "end_time": {
                "$date": 1705816921000
            },
            "percentage": 99.54779148101807,
            "bytes_to_process": 2342563840,
            "bytes_processed": 2353205248,
            "bytes_issued": 2342563840,
            "pause": null,
            "errors": 0,
            "total_secs_left": null
        },
        "topology": {
            "data": [
                {
                    "name": "fake-uuid-value-dummy-data",
                    "type": "DISK",
                    "path": "/dev/disk/by-partuuid/fake-uuid-value-dummy-data",
 [...]

2024-02-16 05:38 UTC, shamoon approved these changes
Thanks. Yea I think another remnant of your other PR, I moved the pool component. Also it really bugged me that the % didnt line up on the far right, sorry to be crazy.

But works great, thanks

<img width="752" alt="Screenshot 2024-02-15 at 9 29 37 PM" src="https://github.com/gethomepage/homepage/assets/4887959/18687266-6818-4abe-b04d-ed00054c097c">

2024-02-16 05:38 UTC, merged

2024-03-17 10:24 UTC, fayimora commented
I have the same issue as @gco .
```json
[{"id":"tank","name":"tank","healthy":true}]
```

2024-03-19 06:47 UTC, gco commented
@fayimora opened a discussion in #3129