Add Plant-it widget
gethomepage/homepage pull request #2941
Opened 2024-02-19 15:37 UTC by MDeLuise

Implements https://github.com/gethomepage/homepage/discussions/2723
Copy of https://github.com/gethomepage/homepage/pull/2890 (up-votes required number is now reached)
## Type of change
- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:
- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

## Example:
<img width="408" alt="Screenshot 2024-01-21 at 14 08 55" src="https://github.com/gethomepage/homepage/assets/66636702/feaaa2f6-0a5d-41a0-b577-fcc0226545ff">

Example of usage:
```
- Plant-it:
    href: http://localhost:8085/
    description: 🪴 Self-hosted, open source gardening companion app
    widget:
      type: plantit
      url: http://localhost:8085
      key: 7QiFTqEdRguDhPNXxr83F8Obl6HpDTUTNg+7SUJdxn+s34kXfxhxHBTEA96w5NgnfS60so3XY/10YKrRXA6vow==
```

2024-02-19 15:53 UTC, shamoon requested changes

2024-02-19 15:53 UTC, shamoon commented on public/locales/it/common.json
Oh I missed this. These will get overwritten by crowdin, so changes should be made there instead =)

2024-02-19 15:53 UTC, shamoon commented on docs/widgets/services/planit.md
> +
```suggestion

Learn more about [Plantit](https://github.com/MDeLuise/plant-it).

```

Our docs now include something like this.

2024-02-19 16:04 UTC, MDeLuise commented on docs/widgets/services/planit.md
> +
Added the documentation reference, thanks.

2024-02-19 16:04 UTC, MDeLuise commented on public/locales/it/common.json
Got it, thanks. I'll make sure to update the translations directly in crowdin. Regarding the translations in the file, would you prefer if I remove them entirely or leave them as a reference?

2024-02-20 01:52 UTC, shamoon commented on docs/widgets/services/planit.md
> +  url: http://plant-it.host.or.ip:port
```suggestion
  url: http://plant-it.host.or.ip:port # api port
```

2024-02-20 01:54 UTC, merged