Added support for Minecraft Bedrock edition to the Minecraft widget
gethomepage/homepage pull request #3179
Opened 2024-03-26 02:51 UTC by LojDev

## Proposed change
Updates the current Minecraft widget to be able to load status information from bedrock edition servers also.

Changes:
- switched to [minecraft-server-util-dist](https://www.npmjs.com/package/minecraft-server-util-dist) instead of minecraft-ping-js since minecraft-server-util-dist supports both java and bedrock edition whereas minecraft-ping-js only supports java edition.
- also added the use of a field called 'edition' (see examples below) for users to specify which minecraft edition they are querying. If this field is not specified then the edition will default to java. 
```
- Minecraft Java:
        widget:
            type: minecraft
            url: udp://192.168.1.50:25565
            edition: java

- Minecraft Bedrock:
        widget:
            type: minecraft
            url: udp://192.168.1.51:19132
            edition: bedrock
```
- Updated documentation of the minecraft widget.

Tested my changes against vanilla Minecraft servers, both bedrock and java, that I have selfhosted locally in my network. Also tested against public java and bedrock servers I found [here](https://findmcserver.com/). See image below.

![MC-Test](https://github.com/gethomepage/homepage/assets/30556267/dd1b9644-2893-43d2-b7de-6d235402e2f0)

Config used from screenshot above:
```
---
- Minecraft Servers - Selfhosted:
    - Java - Selfhosted - Ubuntu Server - Without Edition:
        widget:
            type: minecraft
            url: udp://192.168.1.50:25565
    - Java - Selfhosted - Ubuntu Server - With Edition:
        widget:
            type: minecraft
            url: udp://192.168.1.50:25565
            edition: JAVA
    - Bedrock - Selfhosted - Ubuntu Server:
        widget:
            type: minecraft
            url: udp://192.168.1.51:19132
            edition: bedrock

- Minecraft Java Servers - Public:
    - MINR.ORG:
        widget:
            type: minecraft
            url: udp://zero.minr.org:25565
    - TogehterCrafg:
        widget:
            type: minecraft
            url: udp://play.togethercraft.online:25565
            edition: java
    - Simple Survival:
        widget:
            type: minecraft
            url: udp://mc.simplesurvival.gg:25565
            edition: java

- Minecraft Bedrock Servers - Public:
    - Lifeboatt:
        widget:
            type: minecraft
            url: udp://play.lbsg.net:19132
            edition: BEDROCK
    - GamesMC:
        widget:
            type: minecraft
            url: udp://gamesmc.de:19132
            edition: bedrock
    - Minehaus:
        widget:
            type: minecraft
            url: udp://play.mineha.us:19132
            edition: bedrock
```
## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-03-26 06:55 UTC, shamoon requested changes
If you’re replacing the other dependency please remove it. Is there an open FR for this? That’s required

2024-03-26 12:11 UTC, LojDev reviewed
Unused dependency now removed

2024-03-26 12:14 UTC, LojDev commented
There was a feature request [here](https://github.com/gethomepage/homepage/discussions/1179) but it ended up being closed due to the person using some alternate way to get the status of their bedrock server

2024-03-27 06:19 UTC, shamoon commented
This new package is 24x larger than the current one, if gamedig works (as the FR was closed), I guess do we need this?

2024-03-28 12:18 UTC, LojDev commented
So I played around with gamedig and couldnt get it to display the server version which I wanted to have, other than that it seems  to be a solid alternative as well. Plus i think it makes sense to have support for both minecraft versions in the minecraft widget

2024-03-28 12:35 UTC, shamoon commented
Thanks. I do agree it would make sense to have them both supported here but I dont really think it justifies the https://bundlephobia.com/package/minecraft-server-util-dist@5.4.5 vs https://bundlephobia.com/package/minecraft-ping-js@1.0.2

In fact, one could argue we could drop the Minecraft widget altogether in favor of gamedig (we wont).

If you can figure out another way to do this by using a slimmer package (or perhaps none, we'd be open to that), otherwise for now we'll leave this one with gamedig.

Thank you for the contribution

2024-03-28 12:35 UTC, closed without merging

2024-03-29 17:38 UTC, CosminPerRam commented
Hello, node-gamedig maintainer here.
We are still ongoing about releasing the stable 5.0 of the lib and we know that minecraft support is a bit flacky, but we do have plans to make it more stable and more easily usable.

> So I played around with gamedig and couldnt get it to display the server version which I wanted to have [...]

[node-gamedig#532](https://github.com/gamedig/node-gamedig/pull/532) added `version` as a new stabilized field, have you tried the beta of 5.0? if yes and if you have problems with it please make an issue.

2024-03-29 23:19 UTC, shamoon commented
@CosminPerRam thats awesome thank you. Do you guys expect 5.x to be breaking in any way when it’s released, or mostly a drop-in update?

2024-03-29 23:55 UTC, CosminPerRam commented
> to be breaking in any way when it’s released

Yes, but not in many ways, checkout the [migrate ids](https://github.com/gamedig/node-gamedig/blob/master/MIGRATE_IDS.md) doc and the [changelog](https://github.com/gamedig/node-gamedig/blob/master/CHANGELOG.md) for more info, if you'd like to know/talk more we should move this conversation over to our discord server (: