BugFix - TrueNAS Core support for pool stats
gethomepage/homepage pull request #3206
Opened 2024-04-01 01:29 UTC by rgon10

## Proposed change

Correct enablePools for API differences between TrueNAS Core and TrueNAS Scale. 

TrueNAS Scale returns allocated and free at the pool level for pools, where TrueNAS Core returns this information for the individual volumes below the pool. 

### Current /proxy?type=truenas response on Core
```json
{
  "id" : "pool-name",
  "name": "pool-name",
  "healthy": true,
}
```

### Current behavior when `enablePools: true` is set with TrueNAS Core
![image](https://github.com/gethomepage/homepage/assets/3789272/c832a307-ba68-43db-bf03-6ba68d4605df)

### Abbreviated output of pool API on TrueNAS Core

```json
"topology": {
  "data": [
      {
          "type": "RAIDZ2",
          "stats": {
              "size": 123456789123456,
              "allocated": 1234567879,
          },
      },
  ]},                     
```

### Overview
This fix takes the data response and adds it to the the /proxy/type=truenas response.
A second .jsx class is defined to support differentiation between core and scale. 
A default of scale is included to default to the existing behavior if `nasType` is not defined. 

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-04-01 03:15 UTC, shamoon requested changes
Thanks, a couple comments.

One other big thing is its very un-DRY to create the core-pool component. core-pool and scale-pool contain almost identical code so they should remain as one `pool.jsx` and you can pass in an extra parameter or something like that to do the small amount of extra logic required for core.

I also think this wont pass style checks as-is

Edit: does pass lint =)

2024-04-01 03:15 UTC, shamoon commented on src/widgets/truenas/component.jsx
> +        scaleDeployment &&
```suggestion
        widget?.nasType === "scale" &&
```

This whole thing could be an if really, i.e. if enablePools --> scale vs else

2024-04-01 03:15 UTC, shamoon commented on src/widgets/truenas/component.jsx
> +        coreDeployment &&
```suggestion
        widget?.nasType === "core" &&
```

2024-04-01 03:21 UTC, shamoon commented
Also, if you wouldn't mind posting an example API output from your core device so I can at least test that out (and useful for future reference). Eg. https://github.com/gethomepage/homepage/pull/2908#issuecomment-1947759182

2024-04-01 03:55 UTC, rgon10 commented
Thank you for the initial review and the comments. Your comment about an if/else sparked an idea on how to handle the update in a cleaner manner. 

I've pushed an additional commit, which hopefully makes more sense than the two file approach. 

Please let me know if you have any additional suggestions. 

Full API output is below.

```
[
    {
        "id": 1,
        "name": "r510-hot",
        "guid": "6556082935218011584",
        "encrypt": 0,
        "encryptkey": "",
        "path": "/mnt/r510-hot",
        "status": "ONLINE",
        "scan": {
            "function": "SCRUB",
            "state": "FINISHED",
            "start_time": {
                "$date": 1711864806000
            },
            "end_time": {
                "$date": 1711933573000
            },
            "percentage": 99.87462759017944,
            "bytes_to_process": 47897138294784,
            "bytes_processed": 47957264142336,
            "bytes_issued": 47897138294784,
            "pause": null,
            "errors": 0,
            "total_secs_left": null
        },
        "topology": {
            "data": [
                {
                    "type": "RAIDZ2",
                    "path": null,
                    "guid": "1535553132487403937",
                    "status": "ONLINE",
                    "stats": {
                        "timestamp": 1215877933914035,
                        "read_errors": 0,
                        "write_errors": 0,
                        "checksum_errors": 0,
                        "ops": [
                            0,
                            1614206072,
                            242171406,
                            0,
                            0,
                            0,
                            0
                        ],
                        "bytes": [
                            0,
                            75253679603712,
                            5722574843904,
                            0,
                            0,
                            0,
                            0
                        ],
                        "size": 47828755808256,
                        "allocated": 32456332099584,
                        "fragmentation": 22,
                        "self_healed": 0,
                        "configured_ashift": 12,
                        "logical_ashift": 9,
                        "physical_ashift": 12
                    },
                    "children": [
                        {
                            "type": "DISK",
                            "path": "/dev/gptid/6d24d093-8f61-11ec-904a-782bcb6f2f8e",
                            "guid": "8696719541792796358",
                            "status": "ONLINE",
                            "stats": {
                                "timestamp": 1215877934043103,
                                "read_errors": 0,
                                "write_errors": 0,
                                "checksum_errors": 0,
                                "ops": [
                                    0,
                                    133772879,
                                    26664693,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "bytes": [
                                    0,
                                    9521700507648,
                                    717204451328,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "size": 0,
                                "allocated": 0,
                                "fragmentation": 0,
                                "self_healed": 0,
                                "configured_ashift": 12,
                                "logical_ashift": 9,
                                "physical_ashift": 12
                            },
                            "children": [],
                            "device": "da0p2",
                            "disk": "da0",
                            "unavail_disk": null
                        },
                        {
                            "type": "DISK",
                            "path": "/dev/gptid/2c4fb61c-7a61-11ed-87a9-782bcb6f2f8f",
                            "guid": "2947882732905558508",
                            "status": "ONLINE",
                            "stats": {
                                "timestamp": 1215877934124679,
                                "read_errors": 0,
                                "write_errors": 0,
                                "checksum_errors": 0,
                                "ops": [
                                    0,
                                    234243268,
                                    30802385,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "bytes": [
                                    0,
                                    9347680493568,
                                    715055337472,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "size": 0,
                                "allocated": 0,
                                "fragmentation": 0,
                                "self_healed": 0,
                                "configured_ashift": 12,
                                "logical_ashift": 9,
                                "physical_ashift": 12
                            },
                            "children": [],
                            "device": "da10p2",
                            "disk": "da10",
                            "unavail_disk": null
                        },
                        {
                            "type": "DISK",
                            "path": "/dev/gptid/de5740eb-d600-11ee-9e4e-782bcb6f2f8e",
                            "guid": "6605496022463082297",
                            "status": "ONLINE",
                            "stats": {
                                "timestamp": 1215877934206813,
                                "read_errors": 0,
                                "write_errors": 0,
                                "checksum_errors": 0,
                                "ops": [
                                    0,
                                    192365816,
                                    29278130,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "bytes": [
                                    0,
                                    9415930576896,
                                    715754217472,
                                    0,
                                    0,
                                    0,
                                    0
                                ],
                                "size": 0,
                                "allocated": 0,
                                "fragmentation": 0,
                                "self_healed": 0,
                                "configured_ashift": 12,
                                "logical_ashift": 9,
                                "physical_ashift": 12
                            },
                            "children": [],
                            "device": "da18p2",
                            "disk": "da18",
                  [...]

2024-04-01 04:26 UTC, shamoon requested changes
Great, yea agree thats much cleaner, thanks.

A couple more small things, which you might want to double-check syntax etc

2024-04-01 04:26 UTC, shamoon commented on src/widgets/truenas/component.jsx
> +            scaleFree={pool.free}
```suggestion
            allocated={pool.allocated}
            free={pool.free}
```

Just a nit to rename these

2024-04-01 04:26 UTC, shamoon commented on src/widgets/truenas/pool.jsx
> +
```suggestion
export default function Pool({ name, free, allocated, healthy, data, nasType }) {
  let total = 0;
  if (nasType === "scale") {
    total = free + allocated;
  } else {
    allocated = 0;  // eslint-disable-line no-param-reassign
    for (let i = 0; i < data.length; i += 1) {
      total += data[i].stats.size;
      allocated += data[i].stats.allocated;  // eslint-disable-line no-param-reassign
    }
  }

```

2024-04-01 04:26 UTC, shamoon commented on src/utils/config/service-helpers.js
> +          cleanedService.widget.nasType = nasType ?? "scale";
```suggestion
          if (nasType !== undefined) cleanedService.widget.nasType = nasType;
```

Sorry for the second change here but I'd like to keep the default value encapsulated to the widget itself, not in service-helpers.

2024-04-01 04:26 UTC, shamoon commented on docs/widgets/services/truenas.md
> +
```suggestion
To use the `enablePools` option with TrueNAS Core, the `nasType` parameter is required.

```

2024-04-01 04:26 UTC, shamoon commented on docs/widgets/services/truenas.md
> +  nasType: scale # defaults to scale, values are core or scale
```suggestion
  nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
```

2024-04-01 04:26 UTC, shamoon commented on src/widgets/truenas/component.jsx
> +            nasType={widget?.nasType}
```suggestion
            nasType={widget?.nasType ?? "scale"}
```

2024-04-01 19:50 UTC, rgon10 commented
Pulled in the requested changes and validated the widget is still working as expected with Core. 
Thank you for the assistance. 
Let me know if you see anything else!

2024-04-01 21:32 UTC, shamoon approved these changes
Awesome, thanks.

<img width="752" alt="Screenshot 2024-04-01 at 2 29 16 PM" src="https://github.com/gethomepage/homepage/assets/4887959/f62cb55e-6807-428e-9e4d-2c3ce55b8fc7">
<img width="750" alt="Screenshot 2024-04-01 at 2 28 58 PM" src="https://github.com/gethomepage/homepage/assets/4887959/a763779d-3f86-41ac-9e22-e9669c348c99">

2024-04-01 21:32 UTC, merged

2024-04-06 08:32 UTC, aroundmyroom commented
How can I check why this feature does not work for me?
it only shows still the systemload, uptime and alerts

I have the commit active and available .. 

commit 4e69ea6088839c19a7242a4d05d97ab207927ced
Author: rgon10 <3789272+rgon10@users.noreply.github.com>
Date:   Mon Apr 1 17:32:39 2024 -0400

    Fix: TrueNAS Core support for pool stats (#3206)

my services.yaml shows 

- Shark NAS:
         href: http://nas.local.net
         description: NAS
         icon: truenas.png
         widget:
           type: truenas
           url: http://nas.local.net
           key: xxxxxxxdllwFUy6pgVAQW5rkg2xxxxx
           enablePools: true
           nasType: core
           # username: xxx # not required if using api key
           # password: xxx # not required if using api key

When saved no errors, but no pools available..

2024-04-06 23:54 UTC, shamoon commented
Please dont post support requests on a closed PR, open a discussion. In general, the more information (logs, etc) you provide the better.