Enhancement: add config option for number of decimal places on bitrate blocks for speedtest-tracker
gethomepage/homepage pull request #3354
Opened 2024-04-23 03:11 UTC by ameerabdallah

## Proposed change
Add new widget configuration option for speedtest-tracker widget to configure the number of decimal places it will print the bitrate at. (`bitrateNumOfDecimalPlaces`)

It will now default to 2 decimal places but can be configured for any non-negative integer. If an invalid value is passed in, it will fallback to the default value.

with `bitrateNumOfDecimalPlaces: 3`:
![image](https://github.com/gethomepage/homepage/assets/24537535/8976096e-622d-42fb-aa2a-ed0df659f02b)

with `bitrateNumOfDecimalPlaces: 0`:
![image](https://github.com/gethomepage/homepage/assets/24537535/7b2674ec-737b-44d8-98fb-9f0945c09ae5)

with `bitrateNumOfDecimalPlaces: -3` (falls back to default):
![image](https://github.com/gethomepage/homepage/assets/24537535/1b0a7ec6-8416-45c6-81b0-8e238683e487)

Closes #1308 (issue)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-04-23 03:19 UTC, ameerabdallah commented on src/widgets/speedtest/component.jsx
> +const DEFAULT_BITRATE_NUM_OF_DECIMAL_PLACES = 2;
can set back to 0 if necessary, but it never really made sense to default to 0 decimal places anyway IMO

2024-04-23 03:28 UTC, shamoon requested changes
Thanks, I think this could be be a bit tighter, see suggestions

2024-04-23 03:28 UTC, shamoon commented on docs/widgets/services/speedtest-tracker.md
> +  bitrateNumOfDecimalPlaces: 3 # default is 2
```suggestion
  bitratePrecision: 3 # default is 0
```

Nit: I'd shorten this, a bit long I think

2024-04-23 03:28 UTC, shamoon commented on src/widgets/speedtest/component.jsx
> +
```suggestion
  let bitratePrecision = (!widget?.bitratePrecision || Number.isNaN(widget?.bitratePrecision) || widget?.bitratePrecision < 0) ? 0 : widget.bitratePrecision

```

2024-04-23 03:28 UTC, shamoon commented on src/widgets/speedtest/component.jsx
> +
```suggestion
```

2024-04-23 03:28 UTC, shamoon commented on src/utils/config/service-helpers.js
> +          bitrateNumOfDecimalPlaces,
```suggestion
          bitratePrecision,
```

Also this list should be alphabetical-ish

2024-04-23 03:28 UTC, shamoon commented on src/widgets/speedtest/component.jsx
> +          decimals: bitrateNumOfDecimalPlaces,
```suggestion
          decimals: bitratePrecision,
```

2024-04-23 03:28 UTC, shamoon commented on src/widgets/speedtest/component.jsx
> +          decimals: bitrateNumOfDecimalPlaces,
```suggestion
          decimals: bitratePrecision,
```

2024-04-23 03:28 UTC, shamoon commented on src/utils/config/service-helpers.js
> +        }
```suggestion
        if (type === "speedtest") {
          if (bitratePrecision !== undefined) {
            cleanedService.widget.bitratePrecision = parseInt(bitratePrecision, 10);
          }
        }
```

Dont bother with this if youre going to check the value later anyway.

2024-04-23 03:29 UTC, JManDoo approved these changes
Looks good to me

2024-04-23 03:30 UTC, shamoon commented on src/widgets/speedtest/component.jsx
> +const DEFAULT_BITRATE_NUM_OF_DECIMAL_PLACES = 2;
Theres no reason to change this if we're adding an explicit option to control it. Our users tend to... complain when things change without asking

2024-04-23 03:40 UTC, ameerabdallah commented on src/widgets/speedtest/component.jsx
> +
this is a bit cleaner, thanks

2024-04-23 03:41 UTC, ameerabdallah commented on src/utils/config/service-helpers.js
> +          bitrateNumOfDecimalPlaces,
by service widget name right?

2024-04-23 03:46 UTC, shamoon commented on src/utils/config/service-helpers.js
> +          bitrateNumOfDecimalPlaces,
Yep!

2024-04-23 04:20 UTC, merged

2024-04-29 14:18 UTC, JManDoo reviewed
I agree with the requested changes

2024-04-29 14:22 UTC, shamoon commented
You don’t have privileges to review PRs, and this PR is already merged…