Feature: Wg-Easy Widget
gethomepage/homepage pull request #3476
Opened 2024-05-16 21:22 UTC by ConnerWithAnE

## Proposed change

This adds a widget for Wg-Easy. The widget can display how many Wireguard connections are enabled as well as how many are connected, it also shows total as well and has the option to show disabled. To check for connections the time since the last handshake is checked. It allows for a threshold value in the widget allowing you to adjust how long to wait since the last handshake  in minutes to consider the device connected. It defaults to `["connected", "enabled", "total"]`

Addresses #1580 though I saw this discussion post development. 

![image](https://github.com/gethomepage/homepage/assets/46903591/40ae863b-2039-452b-b043-8531675013db)
![image](https://github.com/gethomepage/homepage/assets/46903591/5a9c6c9a-84a0-4c79-9b38-0fee2f37c5cb)

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-05-17 01:14 UTC, shamoon requested changes
Thanks. Before I review please revert the package changes and the changes to all language files except the English one, the rest will come through the translation tool we use

2024-05-17 01:27 UTC, ConnerWithAnE commented
Oh okay sounds good, didn't know for sure if I needed to fill in the languages or not. I'll fix it tomorrow and push it up.

2024-05-17 03:30 UTC, ConnerWithAnE commented
Seems I somehow roped another commit into here while rebasing but I think it all worked out. Sorry first time doing a rebase.

2024-05-17 03:34 UTC, shamoon commented on docs/configs/settings.md
This commit shouldn’t be here. You can revert this one and squash them all into 1 commit

2024-05-17 04:13 UTC, shamoon commented
Please allow me access to the PR or your fork if needed, I'll sort it out

2024-05-17 04:17 UTC, ConnerWithAnE commented
> Please allow me access to the PR or your fork if needed, I'll sort it out

Apologies, I am trying to revert but it keeps giving me conflicts and just wont let me pull it out. I must be doing something wrong. Again sorry, still getting the hang of it.

2024-05-17 04:47 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +        }
This doesnt really make sense. `login` returns an array, so `sid` will always be [status, ...]

2024-05-17 04:52 UTC, shamoon requested changes
Thanks, mostly minor stuff

2024-05-17 04:52 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +      }
This doesnt really make sense. `login` returns an array, so `sid` will always be [status, ...]

2024-05-17 04:52 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +  return [status, connectSidCookie ?? null];
Why the `?? null`? Thats almost certainly not going to do anything useful

2024-05-17 04:52 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +  const [status, contenType, data, responseHeaders] = await httpProxy(url, {
```suggestion
  const [status, , , responseHeaders] = await httpProxy(url, {
```

2024-05-17 04:52 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +      const [status, contentType, data, responseHeaders] = await httpProxy(
```suggestion
      const [, , data, ] = await httpProxy(
```

2024-05-17 04:52 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +          method: "GET",
```suggestion
```

2024-05-17 04:52 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +      }
This is sorta weird to do in proxy not the component, but anyway:

```suggestion
      dataParsed.push({ threshold: widget.threshold ?? 2 });
```

2024-05-17 04:57 UTC, ConnerWithAnE commented on src/widgets/wgeasy/proxy.js
> +      }
Yea I also thought that but upon removal it seemed to break things. Its annoying since it just returns 204 when successfully logged in.

2024-05-17 04:58 UTC, ConnerWithAnE commented on src/widgets/wgeasy/proxy.js
> +      }
yea when I tried to grab it in the component it did not seem to be there. Thought data should be handled in the proxy anyway so went with it.

2024-05-17 05:00 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +  return [status, connectSidCookie ?? null];
```suggestion
  try {
    const connectSidCookie = responseHeaders["set-cookie"]
      .find((cookie) => cookie.startsWith("connect.sid="))
      .split(";")[0]
      .replace("connect.sid=", "");
    cache.put(`${sessionSIDCacheKey}.${service}`);
    return connectSidCookie;
  } catch (e) {
    logger.error(`Error logging into wg-easy`);
    cache.del(`${sessionSIDCacheKey}.${service}`);
    return null;
  }
```

2024-05-17 05:01 UTC, shamoon commented on src/widgets/wgeasy/proxy.js
> +  return [status, connectSidCookie ?? null];
You were also not putting anything in the cache value

2024-05-17 05:26 UTC, shamoon approved these changes
<img width="758" alt="Screenshot 2024-05-16 at 9 08 35 PM" src="https://github.com/gethomepage/homepage/assets/4887959/23ae8496-bea9-430a-9b82-75737a3bd30d">

Thanks

2024-05-17 05:26 UTC, merged

2024-06-03 12:32 UTC, matox2542080 commented
I just configure this widget, in my case when a von its connected doesn't  appear connected, im the only one?

2024-06-03 15:35 UTC, shamoon commented
A discussion.

2024-06-03 16:05 UTC, matox2542080 commented
WG-Easy:
        icon: wireguard.svg
        href: http://182.17.0.233:51821
        description: Wireguard VPN
        widget:
          type: wgeasy
          url: http://182.17.0.233:51821
          password: xxxxxxxx
          threshold: 1


![Screenshot 2024-06-03 at 1 01 17 PM](https://github.com/gethomepage/homepage/assets/171398189/4492f698-3a75-41b4-8236-499d360a32ff)

2024-06-03 16:06 UTC, matox2542080 commented
When a vpn its connected does not apear connected

2024-06-03 16:22 UTC, shamoon commented
A new discussion thread, not this PR