Feature: add stock market data widget
gethomepage/homepage pull request #3617
Opened 2024-06-09 22:34 UTC by eldyl

## Proposed change

Hello!

I have been working on an implementation of a stock market widget.

Relevant Feature Request -  https://github.com/gethomepage/homepage/discussions/297

![widget_stocks_screenshot](https://github.com/gethomepage/homepage/assets/61209222/0f81dfed-d317-4a59-8065-b46ab429a9fa)

![homepage_widget_stocks_demo](https://github.com/gethomepage/homepage/assets/61209222/eb6a0516-5933-4e43-8d0e-aa5c5f5a1534)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [x] Other (please explain) **Information widget**

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

## Notes
- I felt like this widget fit best as an info widget, but I am happy to change things if the category is not appropriate.
- My goal was to show basic information in a simple way.
- Uses [Finnhub.io's](https//finnhub.io) API. You can sign up for a free API key.
	- [Finnhub allows up to 30 calls per second](https://finnhub.io/docs/api/rate-limit). I set the max items in the watchlist to 30 for this reason. This is a very high number, but I figured I would leave this up to the user.
	- [Finnhub allows up to 60 calls per minute](https://finnhub.io/pricing) on the free tier. I set default caching for this widget to 1 minute. Caching can be changed in the config.
- You can click on the widget to switch between the current price of a stock and the change in price of the stock since open.
- I created the widget as the "Stocks" widget rather than "Finnhub". The intention was to allow different APIs as providers. It should be relatively straightforward to implement more APIs.

Desktop

![homepage_widget_stocks_desktop](https://github.com/gethomepage/homepage/assets/61209222/bdad0e1f-bdbf-4fa8-a33a-28d00629b3a9)

Mobile

![homepage_widget_stocks_mobile](https://github.com/gethomepage/homepage/assets/61209222/61f89a56-fcb3-4ee0-a627-63d8cf66b4ae)

2024-06-10 02:04 UTC, shamoon requested changes
Thanks, this is great overall and I think people will be happy with it. Especially like that its extensible.

A couple small things before I double-check the code is that as-is this will allow duplicates in the list (thats prob OK, people can do crazy things, then again it'd be easy enough to solve) but Im also wondering if the limit of 30 (which I know comes from the API) is too much. It just starts to get too large. Maybe thats OK but my gut tells me we should trim it down. What do you think? 

![Screenshot from 2024-06-09 18-56-25](https://github.com/gethomepage/homepage/assets/4887959/c433d127-a774-4478-bd64-dba2f2f3c9d3)

2024-06-10 05:05 UTC, eldyl commented
I appreciate your feedback!

> as-is this will allow duplicates in the list 

I will take care of this.

> Im also wondering if the limit of 30 (which I know comes from the API) is too much. It just starts to get too large. Maybe thats OK but my gut tells me we should trim it down. What do you think?

Example with 6 Items
![6](https://github.com/gethomepage/homepage/assets/61209222/039d909b-94de-4be0-95da-b3bac4db31ef)

Example with 8 Items
![8](https://github.com/gethomepage/homepage/assets/61209222/e7c40db0-464c-4410-8fea-ca67944a22e8)


Agreed. A max of 6 kind of feels like the sweet spot.  With a known max, I would also like to handle some viewport sizes a little differently. 

If it works, I can have these updates included tomorrow.

If there is anything else that looks like it could be improved, I am happy to make the changes.

2024-06-10 06:17 UTC, shamoon commented
Yea no problem, sounds good on all accounts. I’ll take a look at the code more closely after you push the changes but overall seems like pretty a clean PR thanks 👍

2024-06-10 07:43 UTC, brhahlen commented
Yay! Love this!
My only question would be if it would be possible to make a service widget for it? Would fit better with the CMC widget as welll :)
Thanks for the hard work!

2024-06-10 15:55 UTC, eldyl commented
> Yay! Love this! My only question would be if it would be possible to make a service widget for it? Would fit better with the CMC widget as welll :) Thanks for the hard work!

I could do both.

The component looks like it is pretty easily adaptable:
https://github.com/gethomepage/homepage/blob/main/src/widgets/coinmarketcap/component.jsx 

@shamoon What are your thoughts? Would it be better to pick one? Or would it be reasonable to have both component types as potential options?

2024-06-10 15:56 UTC, shamoon commented
It's not clear from the FR if people want a service widget or info, so it's of course debatable. But given this is closest to the CoinMarketCap widget (which btw is better suited to the list format) perhaps that is the better way to go, sorry for the changeup.

2024-06-10 16:08 UTC, eldyl commented
Happy to make the change. I agree that the format of the CoinMarketCap widget does work better overall. I can get started later today.

2024-06-14 08:15 UTC, benphelps commented
I think both should be options.

On the layout of the info widget, I think keeping the font size the same, and lowering the opacity of the price, would be more inline with the Homepage design direction.  This would also allow it to use slightly less vertical space.

2024-06-14 18:07 UTC, eldyl commented
> I think both should be options.

For my personal use, I do prefer having a few items in the header in most instances.

> On the layout of the info widget, I think keeping the font size the same, and lowering the opacity of the price, would be more inline with the Homepage design direction. This would also allow it to use slightly less vertical space.

I will look into these changes. Thanks for the tips.

---

Apologies for the delay. I have been busy with work :)

I was testing some other APIs to see if it makes sense to include them in the widget, but I think, at least for now, Finnhub seems like a better option with their free tier and limits.

I also have tested getting data from `https://finance.yahoo.com/quotes/${comma_separated_list_of_tickers}`. This would work without an API key, but will require some more processing. I have been testing headers to reduce the size of the received payload. 

I suggested this could be a `Stocks`, widget, and I'd like to make that work, but I would like to provide proof of concept with multiple APIs. Otherwise, it might make sense for for the Widget to be a `Finnhub` widget. I also want to make sure it won't be difficult to maintain multiple APIs. That being said, if changes in the future are accepted, I am happy to help maintain them.

2024-06-14 22:44 UTC, shamoon commented
I would just focus on this version, especially given it will now support two versions of the widget let’s keep the PR focused ie MVP. I’m confident this can be adapted for other APIs if there is need

2024-06-17 07:11 UTC, eldyl commented
> I think both should be options.
> 
> On the layout of the info widget, I think keeping the font size the same, and lowering the opacity of the price, would be more inline with the Homepage design direction. This would also allow it to use slightly less vertical space.

Maybe something closer to this?

![homepage_stock_info_preview_1](https://github.com/gethomepage/homepage/assets/61209222/2404c759-1297-43c6-ae1d-52581b7e3230)

2024-06-18 13:36 UTC, arminius-smh commented
> Example with 6 Items ![6](https://private-user-images.githubusercontent.com/61209222/338056644-039d909b-94de-4be0-95da-b3bac4db31ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTY4MTcsIm5iZiI6MTcxODcxNjUxNywicGF0aCI6Ii82MTIwOTIyMi8zMzgwNTY2NDQtMDM5ZDkwOWItOTRkZS00YmUwLTk1ZGEtYjNiYWM0ZGIzMWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzMTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOWYxMWZiNjc2MGRkYTdjMzgyMWQ5MTVhY2Y1MzcwNWQ4YWRjYmJiZGQ4MGU3MTc5Yjg0YmRkNjE5MmRhNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YfvsqhWs1La29DCUnoukMgAsSCK-qcZjISR4-onSNpA)
> 
> Example with 8 Items ![8](https://private-user-images.githubusercontent.com/61209222/338056674-e7c40db0-464c-4410-8fea-ca67944a22e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTY4MTcsIm5iZiI6MTcxODcxNjUxNywicGF0aCI6Ii82MTIwOTIyMi8zMzgwNTY2NzQtZTdjNDBkYjAtNDY0Yy00NDEwLThmZWEtY2E2Nzk0NGEyMmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzMTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZDIyZmEzYzhjZDVhZmE5NTBiNzE4MzQ1ODVhMmJkOWM3OGJkYTE2NjRiNThhOGI3YjllMGI3OTJhN2ZmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DtmjKQytSSgTGbet5O0OujR0L0YC38olWhgrFrGQK3E)
> 
> Agreed. A max of 6 kind of feels like the sweet spot. With a known max, I would also like to handle some viewport sizes a little differently.

Could this be reconsidered? For example, I don't use the resource monitors and have only the uptime there, so I have more space. 

The greeting info also allows me to write a paragraph in 4xl size in there if I want, I'd be cool if I want to have my header cluttered with stock info to be able to do that.

2024-07-01 05:30 UTC, eldyl commented
I will write with some more information in the morning regarding some of the choices I made, but this should be ready for review.

![mobile](https://github.com/gethomepage/homepage/assets/61209222/d7e00d16-d9ce-4258-94bb-b0fc58beb51e)
![desktop](https://github.com/gethomepage/homepage/assets/61209222/938a15e1-d118-4632-9a8e-7d5390e4378c)

2024-07-01 06:20 UTC, eldyl commented on docs/widgets/info/stocks.md
> +The Stocks Inormation Widget allows you to include basic stock market data in
typo here

2024-07-01 06:36 UTC, shamoon commented
Looking good. Small thing, I wouldn’t bother with displaying (or translating) the errors or displaying things like has duplicates, it’s basically a config error so just throw an error with details in the log and / or truncate the list / remove the duplicates.

2024-07-01 14:48 UTC, shamoon requested changes
I havent tested yet, just some thoughts looking at the code. Thanks

2024-07-01 14:48 UTC, shamoon commented on src/components/widgets/stocks/stocks.jsx
> +  }
```suggestion
  if (data?.error || error) {
    return (
      <Container options={options} additionalClassNames="information-widget-error">
        <PrimaryText>{error ? error : data?.error}</PrimaryText>
        <WidgetIcon icon={BiError} size="l" />
      </Container>
    );
  }
```

Combine these two, also cant translate the error

2024-07-01 14:48 UTC, shamoon commented on src/components/widgets/stocks/stocks.jsx
> +            onClick={() => (viewingPercentChange ? setViewingPercentChange(false) : setViewingPercentChange(true))}
```suggestion
            onClick={() => setViewingPercentChange(!viewingPercentChange)}
```

2024-07-01 14:48 UTC, shamoon commented on src/components/widgets/stocks/stocks.jsx
> +            <div className="flex flex-wrap items-center gap-0.5">{stocks}</div>
I think its a little more react-y to move the above `map` block to here, rather than save it to a const which is used once. Not a big thing, of course

2024-07-01 14:48 UTC, shamoon commented on src/components/widgets/stocks/stocks.jsx
> +  return <Widget options={{ ...options }} />;
Same sorta thing, why not just move `Widget` component in here?

2024-07-01 14:48 UTC, shamoon commented on src/pages/api/widgets/stocks.js
> +    return res.status(400).json({ error: "stocks.hasDuplicates" });
see https://github.com/gethomepage/homepage/pull/3617#issuecomment-2199350926

2024-07-01 14:48 UTC, shamoon commented on src/pages/api/widgets/stocks.js
> +    return res.status(400).json({ error: "stocks.missingWatchlist" });
see https://github.com/gethomepage/homepage/pull/3617#issuecomment-2199350926

2024-07-01 14:48 UTC, shamoon commented on src/widgets/stocks/component.jsx
> +  }
See https://github.com/gethomepage/homepage/pull/3617#issuecomment-2199350926
Also I think these can be combined

2024-07-01 14:48 UTC, shamoon commented on src/widgets/stocks/component.jsx
> +}
Why not the same as the other one, just using `Set`?

2024-07-01 14:58 UTC, eldyl commented
Reviewing now. Thank you for these great  suggestions. I will try and get them all added today.

2024-07-01 15:05 UTC, eldyl commented on src/widgets/stocks/component.jsx
> +}
I will change this to act similarly as the other check. I was going on a journey to add some more features, but then I thought KISS.

I was looking at adding quantities to the service widget. I could add something like this in a future PR, but I have tabled it for now.

This is what it looked like going down that road: 

```js
function parseWatchlist(watchlist) {
  let watchlistNumberOfFieldsWithQuantity = 0;
  let watchlistHasDuplicates = false;
  let dupeCheckMap = new Map();

  // Parse quantity if it exists, and check for duplicates
  const parsedWatchlist = watchlist.map((ticker) => {
    const tickerAndQuantity = ticker.split("*");

    const tickerSymbol = tickerAndQuantity[0];
    const quantity = tickerAndQuantity[1] ? tickerAndQuantity[1] : null;

    if (quantity) watchlistNumberOfFieldsWithQuantity += 1;

    if (dupeCheckMap.has(tickerSymbol)) {
      watchlistHasDuplicates = true;
    } else {
      dupeCheckMap.set(tickerSymbol);
    }

    return {
      ticker: tickerSymbol,
      quantity,
    };
  });

  dupeCheckMap = null;

  return { watchlistHasDuplicates, watchlistNumberOfFieldsWithQuantity, parsedWatchlist };
}
```

2024-07-01 15:07 UTC, shamoon commented on src/widgets/stocks/component.jsx
> +}
Yea good call, this is a big PR already. Get it shipped, watch for bugs, iterate if there's interest =)

2024-07-01 16:07 UTC, eldyl commented on src/components/widgets/stocks/stocks.jsx
> +  }
Should I simplify to use the Error component? 

```
  if (error || data?.error) {
    return <Error options={options} />;
  }

```

https://github.com/gethomepage/homepage/blob/810c321881d9acdde3666c4cac0fd6700d12735b/src/components/widgets/openmeteo/openmeteo.jsx#L20 

https://github.com/gethomepage/homepage/blob/810c321881d9acdde3666c4cac0fd6700d12735b/src/components/widgets/longhorn/longhorn.jsx#L15

https://github.com/gethomepage/homepage/blob/810c321881d9acdde3666c4cac0fd6700d12735b/src/components/widgets/glances/glances.jsx#L33

2024-07-01 16:34 UTC, shamoon commented on src/components/widgets/stocks/stocks.jsx
> +  }
Yea sounds good

2024-07-01 17:23 UTC, eldyl commented
> I havent tested yet, just some thoughts looking at the code. Thanks

Mentioned issues should be resolved: https://github.com/gethomepage/homepage/compare/878d62b1f832f17bb57d18ac3b00ad70dec0c2df..ae3df9eeeb045f256bce33751d1d504ca96cf6cd

2024-07-02 00:16 UTC, shamoon approved these changes
Great work, I think people will dig this. some minor tweaks but nothing major
<img width="292" alt="Screenshot 2024-07-01 at 5 06 49 PM" src="https://github.com/gethomepage/homepage/assets/4887959/0c47aca9-875a-4e5f-8f7e-7498b2552cfc">
<img width="615" alt="Screenshot 2024-07-01 at 5 06 57 PM" src="https://github.com/gethomepage/homepage/assets/4887959/ddb10cdb-9a9a-4fb0-8d19-1e8e332864dc">

2024-07-02 00:16 UTC, merged

2024-07-02 00:37 UTC, eldyl commented
> Great work, I think people will dig this. some minor tweaks but nothing major <img alt="Screenshot 2024-07-01 at 5 06 49 PM" width="292" src="https://private-user-images.githubusercontent.com/4887959/344836246-0c47aca9-875a-4e5f-8f7e-7498b2552cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODA3MjQsIm5iZiI6MTcxOTg4MDQyNCwicGF0aCI6Ii80ODg3OTU5LzM0NDgzNjI0Ni0wYzQ3YWNhOS04NzVhLTRlNWYtOGY3ZS03NDk4YjI1NTJjZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDAzMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE2Zjk3NDk4ZGIyZDY1NGM3MGQ1NzA5MzAyZjBlMDNlOTVkZWI2YzU4Njk2ZDAwNDFlYTFlODg1ZWE4NTRjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FRvbkWEQ2PrHe4bHLsHvOsK8meMdOwQKyAJzXdhIJhg"> <img alt="Screenshot 2024-07-01 at 5 06 57 PM" width="615" src="https://private-user-images.githubusercontent.com/4887959/344836250-ddb10cdb-9a9a-4fb0-8d19-1e8e332864dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODA3MjQsIm5iZiI6MTcxOTg4MDQyNCwicGF0aCI6Ii80ODg3OTU5LzM0NDgzNjI1MC1kZGIxMGNkYi05YTlhLTRmYjAtOGQxOS0xZThlMzMyODY0ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDAzMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDkzMzlkYTRhOGFlZDVkM2ZkYjFmYWIzNjQ2Y2E1M2I5MzQ4YWZlNjQyNjhkNTgzNmVhYzA5NDZhNDllZjYxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UrQdP7dEZqSwlFqZ0N50WcUI9X47q0ij3sBgzSwLOa0">

Thanks again for your feedback throughout. I checked your changes, and I made some notes for myself as well.

Thanks!

2024-07-19 14:38 UTC, rkmd commented
@eldyl - thank you for this wonderful addition to Homepage! Similar to what you've done in the widget box with displaying the percentage price change (instead of the actual price), could this be an option for the information option in the top bar?

Just a suggestion!

2024-08-08 19:27 UTC, suicidaleggroll commented
> Is it possible to add crypto?

FYI - the implemented stock tracker already supports crypto.  While not explicitly called out, you can use "ETH-USD" or "BTC-USD", etc. for your tickers and it works correctly.

```
- stocks:
    provider: finnhub
    color: true
    cache: 1
    watchlist:
      - VOO
      - COIN
      - ETH-USD
      - BTC-USD
```

2024-08-08 22:59 UTC, eldyl commented
> FYI - the implemented stock tracker already supports crypto. While not explicitly called out, you can use "ETH-USD" or "BTC-USD", etc. for your tickers and it works correctly.
> 
> ```
> - stocks:
>     provider: finnhub
>     color: true
>     cache: 1
>     watchlist:
>       - VOO
>       - COIN
>       - ETH-USD
>       - BTC-USD
> ```
> 

I appreciate you sharing this! I was not aware these symbols received proper values from the Finnhub API. I think it would be a good idea to put in a PR for the widget documentation.

```
- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
      - GME
      - AMC
      - NVDA
      - AMD
      - TSM
      - MSFT
      - BTC-USD
      - ETH-USD
```

Something like the above might help point out how you can query some crypto.

I will have some time within the next week to take a closer look at this.

I hope you are well.

2024-08-10 14:59 UTC, Danie10 commented
Hi @eldyl this is working for me, but I'm not sure if I'm missing something for non-US stocks (syntax) or whether I must open a new issue for a feature. I'm looking to for example list a stock STX40 from Johannesburg stock exchange. Finnhub gives the exchange the code JO. But I tried adding STX40.JO and it gives an API error.

2024-08-21 04:36 UTC, suicidaleggroll commented
> > FYI - the implemented stock tracker already supports crypto. While not explicitly called out, you can use "ETH-USD" or "BTC-USD", etc. for your tickers and it works correctly.
> > ```
> > - stocks:
> >     provider: finnhub
> >     color: true
> >     cache: 1
> >     watchlist:
> >       - VOO
> >       - COIN
> >       - ETH-USD
> >       - BTC-USD
> > ```
> 
> I appreciate you sharing this! I was not aware these symbols received proper values from the Finnhub API. I think it would be a good idea to put in a PR for the widget documentation.
> 
> ```
> - stocks:
>     provider: finnhub
>     color: true # optional, defaults to true
>     cache: 1 # optional, default caches results for 1 minute
>     watchlist:
>       - GME
>       - AMC
>       - NVDA
>       - AMD
>       - TSM
>       - MSFT
>       - BTC-USD
>       - ETH-USD
> ```
> 
> Something like the above might help point out how you can query some crypto.
> 
> I will have some time within the next week to take a closer look at this.
> 
> I hope you are well.

After using this for a bit, I can't recommend the crypto tickers from finnhub unfortunately.  It does work, and during the day the numbers are correct, but after the markets close (before 9:30am or after 4pm Eastern) the crypto prices get wacky.  Sometimes it just throws an API error, sometimes it shows the "close" or "open" price of that day, sometimes it shows a price from 2-3 days ago.  It doesn't seem to follow any pattern that I can decipher.  I have noticed that the ticker values on finnhub's website still appear to be correct, so maybe it's just a problem with the API outside of standard trading hours.