Feature: Frigate service widget
gethomepage/homepage pull request #3743
Opened 2024-07-15 09:02 UTC by j0ton

## Proposed change

Implemented a new [Frigate](https://frigate.video) service widget (Feature Request [#2857](https://github.com/gethomepage/homepage/discussions/2857))

<img width="493" alt="Screenshot 2024-07-15 at 8 34 24 PM" src="https://github.com/user-attachments/assets/4efefa90-b000-4adc-8f6d-5c62e79cfba6">

### Example with `enableRecentEvents` option set to `true`:
<img width="493" alt="Screenshot 2024-07-15 at 8 33 54 PM" src="https://github.com/user-attachments/assets/059eada5-55b3-4b90-9795-6afb4f468399">

### Example of event thumbnail preview on hovering over event:
<img width="493" alt="Screenshot 2024-07-15 at 8 35 13 PM" src="https://github.com/user-attachments/assets/1b0676d1-504d-47e6-9e39-ca6b60099333">

Closes [#2857](https://github.com/gethomepage/homepage/discussions/2857)

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-07-15 13:06 UTC, shamoon commented
Thanks. Please post some example api output for us to test with. And I think the thumbnail part will have to be removed, it really doesn’t comply with our guidelines and we really emphasize consistency

2024-07-15 16:17 UTC, narsaw commented
Homepage Dev please consider leaving in the thumbnail feature. ITs a really big deal to have this feature.

2024-07-15 16:19 UTC, shamoon commented
Homepage is not designed to be a "Swiss-army knife" single tool to replace everything, the widget features are to get a glance into other tools. The thumbnail should be removed. Presumably those events can link to somewhere else, that would be ok.

2024-07-15 19:32 UTC, j0ton commented
> Thanks. Please post some example api output for us to test with. And I think the thumbnail part will have to be removed, it really doesn’t comply with our guidelines and we really emphasize consistency

OK no problem I'll remove the thumbnail and possibly look at linking to the events.
I've attached output for the 2 api calls used: `/api/stats` and `/api/events`
[stats.json](https://github.com/user-attachments/files/16239341/stats.json)
[events.json](https://github.com/user-attachments/files/16239340/events.json)

2024-07-16 08:38 UTC, shamoon requested changes
Thanks. couple small things and I still need to test

2024-07-16 08:38 UTC, shamoon commented on src/widgets/frigate/component.jsx
> +  const percentFormatter = new Intl.NumberFormat(i18n.language, { style: "percent" });
This should be done either by passing in `t`. But also at this point perhaps just moving the `Event` component inside the `map` below. After all, this is only getting used once and its (now) pretty small.

Anyway, so then itd be e.g. `t("common.percent", { value: score })`

2024-07-16 08:38 UTC, shamoon commented on src/widgets/frigate/component.jsx
> +          label={data.num_cameras === 1 ? "frigate.camera" : "frigate.cameras"}
```suggestion
          label="frigate.cameras"
```

2024-07-16 08:38 UTC, shamoon commented on public/locales/en/common.json
> +        "camera": "Camera",
```suggestion
```

2024-07-17 14:09 UTC, shamoon approved these changes
Great thanks

<img width="736" alt="Screenshot 2024-07-17 at 7 06 02 AM" src="https://github.com/user-attachments/assets/3c117090-79d5-470f-850b-cbeaefad36b0">

2024-07-17 14:09 UTC, merged