Feature: Add ESPHome widget authentication
gethomepage/homepage pull request #3846
Opened 2024-08-12 17:30 UTC by juanisierra

## Proposed change

Added support for cookie authentication in the ESPHome widget. This is the only authentication method currently supported by the ESPHome Dashboard.

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-08-12 19:00 UTC, shamoon requested changes
Thanks for the PR

Are you sure this proxy is needed? I’m on my phone but looks like we can just use credentialedProxyHandler and add a clause for this.

also, to keep things standard please use key not cookie, like other widgets, and you can probably just concatenate the “authenticated=“ part

2024-08-12 22:30 UTC, shamoon commented
Can you try this? Feel free to modify / revert / etc.

2024-08-13 11:26 UTC, juanisierra commented
@shamoon Works fine! Thanks for the suggestion and the changes!

2024-08-13 14:40 UTC, shamoon approved these changes

2024-08-13 14:40 UTC, merged