Added widget for DeveLanCacheUI
gethomepage/homepage pull request #3854
Opened 2024-08-14 13:55 UTC by devedse

## Proposed change

Closes: https://github.com/gethomepage/homepage/discussions/3543

![image](https://github.com/user-attachments/assets/ce78bef0-0bb6-4c2a-bdde-667fcb3beeb4)

I already created a PR for this previously but couldn't get things to work back then. In this PR everything is tested locally and works fine.

Also added the icon in a PR to dashboard-icons:
https://github.com/walkxcode/dashboard-icons/pull/766

## Type of change

- [X] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-08-14 14:05 UTC, shamoon commented
Thanks, however:

- Please read the guidelines for opening a PR, this can be reopened later.
- Also, you should only edit the English translation file

2024-08-14 14:13 UTC, devedse commented
Ah, you mean the amount of upvotes on the feature request is top low? I remember it being 5. We'll wait for some more interest to boil up then.

2024-08-15 11:59 UTC, devedse commented
@shamoon , I saw that I have since reached 12 upvotes. Can you give me a list of changes that need to happen in this PR?

Kind regards,
Devedse

2024-08-15 13:25 UTC, shamoon commented
It’s very surprising that a project with a seemingly small audience managed to do that in 12 hours, don’t you think? And not a single comment. Any thoughts?

2024-08-15 14:48 UTC, devedse commented
I asked in the discord of LanCache if people where interested. Apparently they were.

2024-08-15 14:51 UTC, shamoon commented
I’ll review the PR when I have a sec, you can just remove the other lang file changes for now

2024-08-15 15:02 UTC, shamoon requested changes

2024-08-15 15:02 UTC, shamoon commented on docs/widgets/services/develancacheui.md
> +        url: https://develancacheui_api.devedse.duckdns.org #Note _api here
What does this mean? Also, don't use a real URL.
Also fails lint it looks like

2024-08-15 15:02 UTC, shamoon commented on docs/widgets/services/develancacheui.md
> +    icon: /assets/icons/DeveLanCacheUI.png
```suggestion
```

2024-08-15 15:02 UTC, shamoon commented on docs/widgets/services/develancacheui.md
> +    href: https://develancacheui.devedse.duckdns.org
```suggestion
    href: https://develancacheui.host.or.ip
```

2024-08-15 15:02 UTC, shamoon commented on src/widgets/develancacheui/widget.js
> +    "DownloadStats/GetTotalDownloadStats": {
```suggestion
    "stats": {
```

2024-08-15 15:02 UTC, shamoon commented on src/widgets/develancacheui/component.jsx
> +  );
```suggestion
  const { data: downloadStatsData, error: downloadStatsError } = useWidgetAPI(widget, "stats");
```

2024-08-15 15:02 UTC, shamoon commented on docs/widgets/services/develancacheui.md
> +```
```suggestion
```

copypasta I assume

2024-08-15 20:27 UTC, devedse commented on docs/widgets/services/develancacheui.md
> +        url: https://develancacheui_api.devedse.duckdns.org #Note _api here
Rewrote the .md file

2024-08-15 20:30 UTC, devedse commented on src/widgets/develancacheui/component.jsx
> +  );
Fixed

2024-08-15 20:30 UTC, devedse commented on src/widgets/develancacheui/widget.js
> +    "DownloadStats/GetTotalDownloadStats": {
fixed

2024-08-15 20:30 UTC, devedse commented
I think I've resolved all your comments. Feel free to re-review and let me know if there's anything else to be improved.

2024-08-15 23:28 UTC, shamoon approved these changes

2024-08-15 23:28 UTC, merged