fix: mealie api change
gethomepage/homepage pull request #3895
Opened 2024-08-24 16:36 UTC by joncrangle

## Proposed change

Mealie is introducing breaking API changes that are already merged in the "nightly" builds. See https://github.com/mealie-recipes/mealie/pull/3970. The `groups/statistics` endpoint is being deprecated and replaced with a `households/statistics` API.

I modelled the API handling on the Immich implementation https://github.com/gethomepage/homepage/pull/2284 so that if the version is greater or equal to "2", or "nightly" it will use the new endpoint, while keeping the existing endpoint as a fallback.

Closes #

## Type of change

- [ ] New service widget
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-08-25 01:31 UTC, shamoon requested changes
Thanks. We’re going to start moving away from doing it this way because this will cause errors in one case or the other while the version call is pending.

Instead, the way to do this is use the `version` parameter in the widget config. And to be non-breaking it’ll need to default to the current one.

Not as “clean” for sure, but for widgets that don’t use a proxy it’s how we’ll handle stuff like this.

Let me know if that makes sense, and if you can make the changes

2024-08-25 03:22 UTC, shamoon commented on docs/widgets/services/mealie.md
> +  version: 1 # optional, defaults to 1
```suggestion
  version: 2 # only required if version > 1, defaults to 1
```

2024-08-25 04:02 UTC, shamoon approved these changes
Thanks for the PR.

Note: this didn't actually work without my last commit there, always good to test things out. (I did of course):

<img width="1234" alt="Screenshot 2024-08-24 at 8 55 38 PM" src="https://github.com/user-attachments/assets/f54e8b6a-7207-4a26-acc1-d42de6d5141f">
<img width="1220" alt="Screenshot 2024-08-24 at 9 00 47 PM" src="https://github.com/user-attachments/assets/832052d8-35bf-48fd-8b44-a2f05a4df2c1">

2024-08-25 04:02 UTC, merged

2024-09-03 23:34 UTC, mcmasterp commented on docs/widgets/services/mealie.md
> +  version: 1 # optional, defaults to 1
I see no effect when setting this to version: 2. I'm trying to force the widget to retrieve stats but it will only use the v1 groups endpoint