Enhancement: customAPI size formatter
gethomepage/homepage pull request #3898
Opened 2024-08-26 18:59 UTC by jdevera

## Proposed change
This PR introduces a new formatter called `size`, which returns the length of an array or string, or the number of keys in an object. This size is then formatted with the `number` formatter.

Some APIs do not return a summary of their contents, but only the full list of contents. The `size` formatter can be used to still show such count on a widget.

This PR also adds another feature, which is necessary to make the `size` formatted truly flexible: Using a dot (`.`) as a key name to select the top-level of an API response. This is so that we can count the elements of an array when the endpoint only returns an array.

### Example with Cat Facts

This [Open API of Cat facts](https://cat-fact.herokuapp.com/facts) produces an array of objects.

With this configuration:

```yaml
- Animal Group:
    - Cat Facts:
        href: https://alexwohlbruck.github.io/cat-facts/
        description: Cat Facts!
        icon: mdi-cat
        widget:
          type: customapi
          url: https://cat-fact.herokuapp.com/facts
          method: GET
          mappings:
            - field: .
              label: Facts
              format: size
```

You get this:
![Cat facts widget](https://github.com/user-attachments/assets/10246685-e171-4c0e-b6de-685d4bd11714)

Closes #2720 

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
	- [x] Tested on all combinations of iOS and MacOS with Chrome, Safari, and Firefox

2024-08-26 20:19 UTC, shamoon commented
Thanks. `.` is kinda weird, did you try anything like just using the root if no `field` is provided? Feels cleaner

2024-08-26 20:49 UTC, jdevera commented
I took the dot from [jq](https://jqlang.github.io/jq/) because at first I tried with nothing and it seemed more *mysterious* because of the implicit meaning. If the dot is not okay, would you consider something else that is explicit, even if it requires a trip to the documentation?

2024-08-26 22:04 UTC, shamoon commented
It’s not really a question of what the character it’s just that it feels unnecessary to have one at all. `.` feels like a sort of programmer thing, which most of our users are not. Using no field to signify root would allow users to leave off an entire line in their config (I don’t mean `field: ` I mean not even specifying `field` at all)

2024-08-26 22:22 UTC, jdevera commented
Okay I'll give that a spin, I was always thinking of the block with the `field` key.

2024-08-26 22:54 UTC, jdevera commented
Okay so after the changes, this config:

```yaml
- Animal Group:
    - Cat Facts:
        href: https://alexwohlbruck.github.io/cat-facts/
        description: Cat Facts!
        icon: mdi-cat
        widget:
          type: customapi
          url: https://cat-fact.herokuapp.com/facts
          method: GET
          mappings:
            - label: Facts
              format: size
    - Hounds:
        href: https://dog.ceo/api/breed/hound/images
        description: Hounds!
        icon: mdi-dog
        widget:
          type: customapi
          url: https://dog.ceo/api/breed/hound/images
          method: GET
          mappings:
            - label: Images
              format: size
              field: message
```
Shows this:
![Hounds](https://github.com/user-attachments/assets/4ee04341-6843-471e-9d7e-4f710389e294)

2024-08-27 04:01 UTC, shamoon requested changes

2024-08-27 15:05 UTC, shamoon approved these changes
<img width="621" alt="Screenshot 2024-08-27 at 7 54 22 AM" src="https://github.com/user-attachments/assets/040a59bc-178c-47b5-bd44-4f6bd93a9bad">

Thanks

2024-08-27 15:05 UTC, merged

2024-08-27 16:08 UTC, jdevera commented
Thank you for the review!