Feature: Zabbix service widget
gethomepage/homepage pull request #3905
Opened 2024-08-28 21:31 UTC by ping-localhost

## Proposed change

![image](https://github.com/user-attachments/assets/4ba9fb29-20e4-4430-9b7e-60995b53fd25)

The user will be able to add the widget to the `services.yaml` file using the following configuration:

```yaml
widget:
  type: zabbix
  url: http://zabbix.host.or.ip
  key: your-api-key
```

Zabbix exposes 6 fields by default and it requires an `auth`-field in the JSON RPC call, which wasn't possible with the generic jsonrpc proxy, hope this is okay (even though it is against the Service Widget Guidelines).
  
Relevant feature request: https://github.com/gethomepage/homepage/discussions/1953

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [?] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-08-28 23:14 UTC, shamoon requested changes
> I did somewhat break the Service Widget Guidelines.
> 
> Zabbix exposes 6 alert fields by default, but I can cut it down to just 4.
> Zabbix requires an auth-field in the JSON RPC call for API tokens, which I could not figure out how to do with the generic jsonrpc proxy.
>
> Let me know what I should change to have a valid pull request.

Well, you need to change both of those things, that's why we have the guidelines.

Setting up a Zabbix instance to test does not seem trivial, so Im not inclined to do so, but Im certain the existing jsonrpc proxy can be modified to accept body params, or just simply adding logic to use `widget.key` if its supplied instead of username/pw.

2024-08-29 07:01 UTC, ping-localhost commented
> Well, you need to change both of those things, that's why we have the guidelines.

I've removed the two lowest priority fields for now.

> Im certain the existing jsonrpc proxy can be modified to accept body params, or just simply adding logic to use widget.key if its supplied instead of username/pw.

I've tried to do that, by passing the params via the URL itself and then parsing it again within the proxy. Hopefully this is okay.

> Setting up a Zabbix instance to test does not seem trivial

If you're using Proxmox, you could use tteck's proxmox script to setup a [Zabbix LXC](https://github.com/tteck/Proxmox/blob/main/install/zabbix-install.sh).

2024-08-29 18:31 UTC, ping-localhost commented
As long as `Authorization` stays capitalized, I'm happy with the changes in 4a0b18b. Zabbix doesn't accept the API token if the header is `authorization`.

2024-08-29 18:45 UTC, shamoon approved these changes
Awesome, thanks for the quick changes. 

1. I just reverted the change to the headers of the jsonrpc proxy *just in case* it affects other widgets. Presumably your version is more correct but zabbix didn't seem to care (I went ahead and did docker setup, pretty simple actually)
2. Passing arbitrary params is a security vulnerability, so you can look how I've done this, basically they need to be hard-coded into the widget

Obviously let me know if you have any concerns

Thanks
<img width="748" alt="Screenshot 2024-08-29 at 11 44 40 AM" src="https://github.com/user-attachments/assets/35705add-7c88-4b0c-9685-24062f8f4471">

2024-08-29 18:45 UTC, merged

2024-08-29 18:47 UTC, ping-localhost commented
Perfect, thank you for fixing my mistake. I'll make sure to do better on the next widget 😁

2024-08-30 09:19 UTC, adm2k commented
So is this widget usable at this time? I set it up but getting this:
![image](https://github.com/user-attachments/assets/bacc18b0-dc08-4bcd-b255-d9b5afe3a656)

2024-08-30 09:20 UTC, ping-localhost commented
> So is this widget usable at this time? I set it up but getting this: 

There is no new release yet, so it is not available yet.

2024-08-30 09:22 UTC, adm2k commented
Ok, thanks for letting me know...

2024-09-13 11:48 UTC, ping-localhost commented
@adm2k FYI, the widget is now available

2024-09-13 13:33 UTC, adm2k commented
Thanks, working now...