Add Spoolman Widget
gethomepage/homepage pull request #3959
Opened 2024-09-08 11:46 UTC by fgeck

## Proposed change

Adds a Spoolman widget. Each spool will be rendered into a dedicated `<Block>` showing the filament name and remaining filament in %.

Widget:

<img width="675" alt="image" src="https://github.com/user-attachments/assets/1cf65bd8-9557-495d-a95f-975922a5e3f5">

Spoolman:

<img width="1258" alt="image" src="https://github.com/user-attachments/assets/550b3957-322b-48b1-a79b-13ff114d12db">

Closes #3958

## Type of change

- [x] New service widget

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/latest/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/latest/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/latest/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/latest/more/development/#code-linting).

2024-09-08 14:25 UTC, shamoon commented
please review the guidelines. We require demonstration of community interest on the feature request. We can readdress in the future. Thanks

2024-09-08 14:25 UTC, closed without merging

2024-11-20 14:58 UTC, shamoon requested changes
Works great. A couple things, and this needs a re-base.

<img width="881" alt="Screenshot 2024-11-20 at 6 58 32 AM" src="https://github.com/user-attachments/assets/4da88320-39ff-49b7-8d29-9469bfc3a407">

2024-11-20 14:58 UTC, shamoon commented on docs/widgets/services/spoolman.md
> +Spoolman is a self-hosted web service designed to help you efficiently manage your 3D printer filament spools and monitor their usage. It acts as a centralized database that seamlessly integrates wit
```suggestion
```

2024-11-20 14:58 UTC, shamoon commented on src/widgets/spoolman/component.jsx
> +
```suggestion
  if (spoolData.length === 0) {
    return (
      <Container service={service}>
        <Block label="spoolman.noSpools" />
      </Container>
    );
  }

  if (spoolData.length > 4) spoolData = spoolData.slice(0, 4);

```

1. I would handle the no spools case (need to add entry to common.json)
2. We dont allow more than 4 blocks, as noted in the guidelines. So up to you how to handle it, at minimum just slice the 4, or you can change the widget in that case (e.g. show a block with total, some other info, etc)

2024-11-21 07:47 UTC, fgeck commented
started incorporating your feedback yesterday.
Need to test and will push again in the upcoming days.

2024-11-21 20:24 UTC, fgeck commented
Finally again ready for review @shamoon 

I added an option to filter spools by their id.

Spoolman:

<img width="1092" alt="Screenshot 2024-11-21 at 21 15 46" src="https://github.com/user-attachments/assets/a8eec857-7a1b-41cf-b539-1190770dfb3f">

Config:

```yaml
widget:
          type: spoolman
          url: https://spoolsman.io
          spoolIds:
            - 2
            - 5       # does not exist, but is allowed
```

Result in homepage:

<img width="870" alt="Screenshot 2024-11-21 at 21 21 18" src="https://github.com/user-attachments/assets/2f7b4aaa-1446-498f-a754-366c4c1519f1">

2024-11-21 23:02 UTC, shamoon commented
Please have a read about git rebasing or merge commits. We squash commits anyway but this is a very messy history that makes life a bit more complicated for maintainers.