Change moonraker widget standby output
gethomepage/homepage pull request #4060
Opened 2024-09-28 16:42 UTC by ihatemyisp

## Proposed change

Moonraker returns "null" for layer counts when in standby. This causes "null / null" to be displayed. This PR changes that behavior and displays "-" for both the layers and progress blocks (to keep things similar).

![Screenshot 2024-09-28 123810](https://github.com/user-attachments/assets/61a032c0-cea6-4c0d-8c4f-2fa5efe45889)

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [x] Other (please explain)

This is a cosmetic change to an existing service widget.

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-09-28 16:49 UTC, shamoon commented
I’m sorry, we don’t accept change requests that aren’t targeted to a request discussion. Please see the contributing guidelines.

2025-03-19 15:47 UTC, shamoon requested changes
Please rewrite this to just assign the values to a variable rather than adding an entire extra block

2025-03-19 16:11 UTC, shamoon commented
Actually can you post the moonraker API output when the printer is on standby?

2025-03-19 22:30 UTC, ihatemyisp reviewed
This covers changing 'null / null' for the layers, but leaves us with '0%' for the progress. Is there a clean way to change the progress block to '-' when in standby?

2025-03-19 22:31 UTC, ihatemyisp commented
> Actually can you post the moonraker API output when the printer is on standby?

```
{
  "result": {
    "eventtime": 15438012.187811136,
    "status": {
      "print_stats": {
        "filename": "",
        "total_duration": 0,
        "print_duration": 0,
        "filament_used": 0,
        "state": "standby",
        "message": "",
        "info": {
          "total_layer": null,
          "current_layer": null
        }
      }
    }
  }
}
```

2025-03-19 22:36 UTC, shamoon commented
> This covers changing 'null / null' for the layers, but leaves us with '0%' for the progress. Is there a clean way to change the progress block to '-' when in standby?

Oh yea I didnt realize that was an issue too. Can you post all 3 relevant endpoints? print_stats, display_status, webhooks

2025-03-19 22:43 UTC, shamoon commented
Pretty sure its fine just wanted to make sure since I dont actually have one of these to test.

<img width="397" alt="Screenshot 2025-03-19 at 3 40 34 PM" src="https://github.com/user-attachments/assets/04fba7a6-2b44-45cd-bf6e-f09449223e34" />
<img width="381" alt="Screenshot 2025-03-19 at 3 42 04 PM" src="https://github.com/user-attachments/assets/7206336f-d1da-48c4-b90f-c9417d7dcf74" />

You can also just test yourself and let me know this works

2025-03-19 22:58 UTC, ihatemyisp commented
> You can also just test yourself and let me know this works

You beat me to it haha. I got sidetracked figuring out why VSC kept crashing on me. Built the image and it works perfectly.

display_stats and web_hooks both return empty arrays.

Thanks again.

2025-03-19 23:26 UTC, shamoon approved these changes

2025-03-19 23:26 UTC, merged