Feature: Add ArgoCD widget
gethomepage/homepage pull request #4305
Opened 2024-11-17 20:51 UTC by fcornelius

## Proposed change

This adds a widget for [ArgoCD](https://argo-cd.readthedocs.io/en/latest/). It can list the count of apps present in an ArgoCD instance by app status, e.g. `synced` or `healthy`.

<img width="411" alt="image" src="https://github.com/user-attachments/assets/d86661ea-7c08-4bf9-adce-5f9c6cb36dcd">

Closes #2644

## Type of change

- [x] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [x] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-11-17 21:15 UTC, shamoon requested changes
The length of the docs here backs up my theory that k8s is too complicated. If you’d think there’s a way to make it more concise (mostly linking to other places ) that’d be great, I didn’t see anything obvious.

As for the widget, if you wouldn’t mind copy pasting some sample api output for me to test.

Finally, one thing is all widgets should display no more than 4 blocks. I’ll have a real look once you have a chance to supply the above.

thanks

2024-11-19 20:15 UTC, fcornelius commented
I feel you, the doc however is not related to kubernetes itself. It's due to the way roles are configured in ArgoCD, which is a little unintuitive and I wanted to include a security best practice rather than just the quickest solution to get it running.

Limited the maximum fields shown to 4 now.

Sample API response to test with: [argocd-api-response.json](https://github.com/user-attachments/files/17820774/argocd-api-response.json)
This one should yield the fields:
`apps`: 4, `synced`: 2, `outOfSync`: 2, `healthy`: 1, `missing`: 1, `degraded`: 1, `progressing`: 1

2024-11-19 20:31 UTC, shamoon commented on src/widgets/prometheusmetric/component.jsx
> +  if (!metric?.format) return rawValue;
Thanks, why is this here btw?

2024-11-19 20:55 UTC, shamoon requested changes
Thanks, seems to work well just some small things.

<img width="876" alt="Screenshot 2024-11-19 at 12 50 03 PM" src="https://github.com/user-attachments/assets/af203462-2ebb-4da5-9fd5-426a6db00b0c">

2024-11-19 20:55 UTC, shamoon commented on src/widgets/argocd/component.jsx
> +  // Limits max number of displayed fields
```suggestion
  if (!widget.fields) {
    widget.fields = ["apps", "synced", "outOfSync", "healthy"];
  }

```

1. we dont do this kind of field validation here
2. At the moment the widget doesn't work if the user doesn't supply any fields, which is pretty common

2024-11-19 20:55 UTC, shamoon commented on src/widgets/argocd/component.jsx
> +      (item) => item.status?.sync?.status === apiStatus || item.status?.health?.status === apiStatus,
```suggestion
    const count = appsData?.items?.filter(
      (item) => item.status?.sync?.status.toLowerCase() === status.toLowerCase() || item.status?.health?.status.toLowerCase() === status.toLowerCase(),
```

2024-11-19 20:55 UTC, shamoon commented on public/locales/en/common.json
> +        "outOfSync": "OutOfSync",
```suggestion
        "outOfSync": "Out Of Sync",
```

2024-11-19 21:33 UTC, fcornelius commented on src/widgets/argocd/component.jsx
> +  // Limits max number of displayed fields
Cool, good to know

2024-11-19 21:46 UTC, shamoon commented on src/widgets/prometheusmetric/component.jsx
> +  if (!metric?.format) return rawValue;
Oh, I didn't realize you're the same person, cool that's fine

2024-11-19 21:58 UTC, fcornelius commented on src/widgets/prometheusmetric/component.jsx
> +  if (!metric?.format) return rawValue;
No problem 😄

2024-11-19 21:59 UTC, shamoon approved these changes
Awesome thanks

2024-11-19 21:59 UTC, merged

2024-11-19 22:03 UTC, fcornelius commented
> Awesome thanks

Thank you for this cool project!