feat: Added active and total for network usage (dw,up) resources.
gethomepage/homepage pull request #4327
Opened 2024-11-25 03:31 UTC by ramazansancar

upd: Docs updated for network usage.
add: Widget resorce iconChildren param added.
upd: config file default options added.
upd: resources units type added.

## Proposed change

Closes #3421 (Discussion)

Addresses Discussion/FR #3421
Old PR: #3420

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [X] If applicable, I have added corresponding documentation changes.
- [X] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [X] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-11-25 03:44 UTC, shamoon requested changes
Thanks. This does need some work. I noted some small things on my phone but I need to take a closer look. It also won’t pass lint at the moment.

2024-11-25 03:44 UTC, shamoon commented on docs/widgets/info/resources.md
> +    units: imperial # only used by cpu temp widget, options: 'imperial' or 'metric'
```suggestion
    units: imperial # only used by cpu temp, options: 'imperial' or 'metric'
```

2024-11-25 03:44 UTC, shamoon commented on src/components/widgets/resources/network.jsx
> +  const { data, error } = useSWR(`/api/widgets/resources?type=network${(options.network || ( options.network !== 'default' && options.network === `false`)) ? `&interfaceName=${options.network}` : ''
Did you really mean to test for network === “false” the string here?

2024-11-25 03:44 UTC, shamoon commented on src/pages/api/widgets/resources.js
> +  let { interfaceName } = req.query;
This presumably should be a const like the others

2024-11-25 03:47 UTC, ramazansancar commented on src/components/widgets/resources/network.jsx
> +  const { data, error } = useSWR(`/api/widgets/resources?type=network${(options.network || ( options.network !== 'default' && options.network === `false`)) ? `&interfaceName=${options.network}` : ''
I wanted to check the case where the value is false and not equal to "default". @shamoon

2024-11-25 03:50 UTC, ramazansancar commented on src/pages/api/widgets/resources.js
> +  let { interfaceName } = req.query;
If we define it as constant const, I cannot change its value and control it in case it comes as default.

https://github.com/gethomepage/homepage/pull/4327/files#diff-0b3b2a1073c6f2cb86bf9a749bc02609827974f397d6847e3f658bcdf551300bR71-R72

2024-11-25 03:55 UTC, ramazansancar commented
> Thanks. This does need some work. I noted some small things on my phone but I need to take a closer look. It also won’t pass lint at the moment.

I will look at the lint issue again. I have provided answers for other change requests.

As an additional feature, I have in mind to separate live network usage and total network usage, i.e. define it separately from the config, what is your opinion on this? (Those who want only one can open it from the config as they wish. Those who want both can add it by writing 2 lines in the config.)

2024-11-25 04:05 UTC, shamoon commented on src/components/widgets/resources/network.jsx
> +  const { data, error } = useSWR(`/api/widgets/resources?type=network${(options.network || ( options.network !== 'default' && options.network === `false`)) ? `&interfaceName=${options.network}` : ''
That's not what this is doing anyway.

2024-11-25 04:06 UTC, shamoon commented on src/pages/api/widgets/resources.js
> +  let { interfaceName } = req.query;
You can initialize it to a default

2024-11-25 04:32 UTC, shamoon requested changes
You can take a look my changes, this is cleaner already.

<img width="275" alt="Screenshot 2024-11-24 at 8 30 18 PM" src="https://github.com/user-attachments/assets/9b4d41f1-7411-470b-8d3c-6ef52c184bce">

But I'm still not happy with the aesthetics.

1. This is the only widget item with two lines by default, which is a problem.
2. Yes, we are not going to show both of them. I'd suggest we make the throughput and totals each their own line and the widget defaults to throughput and the totals is in the 'expanded' version.

2024-11-25 04:52 UTC, ramazansancar commented
> That's not going to work, and will make it overly-complicated. Take a look a the recent changes.
> 
> <img width="882" alt="Screenshot 2024-11-24 at 8 41 05 PM" src="https://github.com/user-attachments/assets/8a1bdb57-8243-411e-ae66-2c50fc94fb5d">
> <img width="908" alt="Screenshot 2024-11-24 at 8 40 22 PM" src="https://github.com/user-attachments/assets/63b913ee-86fd-468a-87ec-834ba2549dc5">
> 
> The final issue here is the percentage bar, which you've just set... to 0?


The most logical thing to do at the moment seems to be to keep it at 0. We can't do anything because we won't have any max data.

2024-11-25 06:35 UTC, shamoon approved these changes
<img width="281" alt="Screenshot 2024-11-24 at 10 30 23 PM" src="https://github.com/user-attachments/assets/2302d67c-f108-49e3-9fae-e294a0f12e7c">

2024-11-25 06:35 UTC, merged

2024-11-26 03:23 UTC, o2e commented
I would like to add a tip, if you want to get the host's NIC information, then the docker container may need to be modified to `network_mode: host`. If you want to modify the port in host network mode, you also need to add `environment: - PORT=3000`(3000 is your port)

2024-11-26 03:27 UTC, o2e commented
> I would like to add a tip, if you want to get the host's NIC information, then the docker container may need to be modified to `network_mode: host`. If you want to modify the port in host network mode, you also need to add `environment: - PORT=3000`(3000 is your port)

I think it would be a good idea to add this note to the documentation, otherwise some newbies might not use it, and at least some of my friends don't know the difference between docker's network modes

2024-11-26 03:33 UTC, shamoon commented
The problem with doing that is it will almost certainly break existing integrations with other containers. It was always my beef with this widget but then again the same can apply to other resources in some situations

2024-11-26 03:52 UTC, o2e commented
Yes, it's a matter of trade-offs. Despite his slight flaws, it's worth it to me because I don't have any other easy and intuitive way to see what's going on with the network. `homepage` serves as the homepage of my browser, the monitor window of my portable screen, and having a small, sophisticated display of network information is great for me, and I can live with a few tweaks for that (I know that Glances has a similar feature, but I don't really like it! )
<img width="699" alt="image" src="https://github.com/user-attachments/assets/d9088513-c580-406b-b3d8-93bf180921a1">

2024-11-26 06:54 UTC, ramazansancar commented
I forgot to thank you. Thanks for supporting the development and pushing it forward at some point. It was a nice feature to the project. @shamoon