Show progress for qbittorrent
gethomepage/homepage pull request #4405
Opened 2024-12-12 20:08 UTC by Mindfreak9100

## Proposed change
This change adds a flag `enableLeechProgress` to the qbittorrent widget. It will show the progress of leech/s as shown in the screenshot. It also shows the status/state of the leech as well as the ETA. 
<img width="497" alt="Screenshot 2024-12-12 at 3 04 25 PM" src="https://github.com/user-attachments/assets/c49cc821-7ca3-4c7d-addb-e0541dcb0708" />

Closes #4374

## Type of change

- [ ] New service widget
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation only
- [ ] Other (please explain)

## Checklist:

- [x] If applicable, I have added corresponding documentation changes.
- [x] If applicable, I have reviewed the [feature](https://gethomepage.dev/more/development/#new-feature-guidelines) and / or [service widget guidelines](https://gethomepage.dev/more/development/#service-widget-guidelines).
- [ ] I have checked that all code style checks pass using [pre-commit hooks](https://gethomepage.dev/more/development/#code-formatting-with-pre-commit-hooks) and [linting checks](https://gethomepage.dev/more/development/#code-linting).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.

2024-12-12 20:38 UTC, shamoon commented
I will take a look at this later thanks. Can’t you just use the duration formatted though, instead of this one you wrote?

2024-12-12 21:45 UTC, shamoon requested changes

2024-12-12 21:45 UTC, shamoon commented on src/widgets/qbittorrent/component.jsx
> +function formatTimeLeft(inputSeconds) {
As I said, pretty certain this can be done with `duration`

2024-12-12 21:45 UTC, shamoon commented on src/widgets/qbittorrent/component.jsx
> +    if (torrent.state.includes("DL") || torrent.state === "downloading") {
Why is this needed?

2024-12-12 21:45 UTC, shamoon commented on src/widgets/qbittorrent/component.jsx
> +            timeLeft={formatTimeLeft(queueEntry.eta)}
Depending on what eta is (seconds from now or a date?), something like `t("common.duration", { value:... })`

2024-12-12 22:36 UTC, Mindfreak9100 commented on src/widgets/qbittorrent/component.jsx
> +            timeLeft={formatTimeLeft(queueEntry.eta)}
I've updated the code to use duration instead. I thought the custom function was better from UI experience but I don't have a preference and I like to have consistency in the code.

2024-12-12 22:39 UTC, Mindfreak9100 commented on src/widgets/qbittorrent/component.jsx
> +    if (torrent.state.includes("DL") || torrent.state === "downloading") {
There are multiple states/status for downloading torrents within qbittorrent. Hence, trying to cover all downloading states/status. 

<img width="676" alt="Screenshot 2024-12-12 at 5 37 17 PM" src="https://github.com/user-attachments/assets/3f115e48-d277-47dc-addd-69f7d24d82a4" />

Documentation: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list

2024-12-12 23:36 UTC, shamoon commented on src/widgets/qbittorrent/component.jsx
> +    if (torrent.state.includes("DL") || torrent.state === "downloading") {
thank makes sense thanks

2024-12-12 23:50 UTC, shamoon requested changes
<img width="594" alt="Screenshot 2024-12-12 at 3 45 27 PM" src="https://github.com/user-attachments/assets/279010ad-a4b5-4f34-a7d3-ea46c2da210a" />

Great thanks, one last thing

2024-12-12 23:50 UTC, shamoon commented on src/widgets/qbittorrent/component.jsx
> +  const enableLeechProgress = widget?.enableLeechProgress && Array.isArray(leechTorrents) && leechTorrents.length > 0;
```suggestion
```

This isn't necessary:

1. you're initializing the array above
2. if the length is 0 the mapping function below won't do anything (which is what you want)

2024-12-12 23:50 UTC, shamoon commented on src/widgets/qbittorrent/component.jsx
> +      {enableLeechProgress &&
```suggestion
      {widget?.enableLeechProgress &&
```

2024-12-12 23:53 UTC, shamoon commented
Actually one more general question: why is this limited to downloading items? Other widgets just enable the queue (all of it) or not, which would be more consistent.

2024-12-13 00:10 UTC, Mindfreak9100 commented
Understand the concept behind being consistent but I think there is more value to show the progress of downloading torrents as compared to showing everything.

The progress for seeding torrents would be always 100%, no ETA as well as the speeds for the upload will be already shown by the widget.let me know if it makes sense.

2024-12-13 00:16 UTC, shamoon commented
Yea, fair enough, if its a big issue for folks we can always revisit.

2024-12-13 00:32 UTC, shamoon approved these changes

2024-12-13 00:32 UTC, merged

2024-12-13 05:15 UTC, Mindfreak9100 commented
Thank you @shamoon for your time and effort for being so actively involved! It's been a wonderful experience contributing to the repo.